Main
bagisto/bagisto pull request #10084
Opened 2024-08-17 10:42 UTC by wahebtalal

## Issue Reference

## Description

## How To Test This?

## Documentation
- [ ] My pull request requires an update on the documentation repository.

## Branch Selection

- [ ] Target Branch: master 

## Pint

## Tailwind Reordering

2024-09-02 08:03 UTC, amit-webkul requested changes

2024-09-02 08:03 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Controllers/SearchController.php
> +            'query' => ['string', 'regex:/^[^\\\\]+$/u'],
Here required should be added.

2024-09-02 08:06 UTC, amit-webkul commented
@wahebtalal 

Thank you for your contribution to Bagisto.

I have reviewed your pull request and added some comments. Please review these comments and update the pull request accordingly. If you have any concerns or questions about the comments, feel free to respond directly to them.

We appreciate your efforts.

2024-09-05 04:20 UTC, amit-webkul commented
Any Updates ?

2024-09-10 05:08 UTC, devansh-webkul commented
Feel free to raise a new PR.

2024-09-10 05:08 UTC, closed without merging