Added improvemnet #10168
bagisto/bagisto pull request #10225
Opened 2024-10-28 07:52 UTC by amit-webkul

## Issue Reference
Added improvement #10168

## Description
Added configuration setting for handling censoring product reviewer names on the product page.

Config path: configuration -> catalog -> products -> Review -> Censoring Reviewer Name

## How To Test This?
You can test with enable or disable the configuration and then check on the product view page in the review section. 

## Branch Selection

- [ ] Target Branch: 2.2

2024-10-28 09:58 UTC, ashishkumar-webkul commented
Checked and found that the setting has been added to the configurations and now it is working fine. Please check the Screenshot for reference.

**Screenshot**

https://prnt.sc/U39pb04P2g99
https://prnt.sc/yoyfCa9cTJdJ
https://prnt.sc/ClaFdiG7CW2F

2024-10-28 10:10 UTC, devansh-webkul commented
We will give this in master.

2024-10-28 10:14 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
>              },
Move this logic to backend. There should be no censoring in the frontend.

2024-10-29 04:11 UTC, devansh-webkul requested changes

2024-10-29 04:11 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/ReviewController.php
> +            });
```php
$productReviews->getCollection()->transform(function ($review) {
    $review->name = $this->censorReviewerName($review->name);
    
    return $review;
});
```

2024-10-29 04:11 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/ReviewController.php
>              ->paginate(8);
```php
$product = $this->productRepository->findOrFail($id);
```

2024-10-29 11:21 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Config/system.php
> +                'title'   => 'Censoring Reviewer Name',
Translation

2024-10-30 05:02 UTC, amit-webkul commented on packages/Webkul/Admin/src/Config/system.php
> +                'title'   => 'Censoring Reviewer Name',
Done sir

2024-11-04 04:15 UTC, merged