:feat: product custom options
bagisto/bagisto pull request #10260
Opened 2024-11-05 07:10 UTC by devansh-webkul

2024-11-05 07:11 UTC, devansh-webkul commented
This pull request is on top of Laravel 11. So first Laravel 11 PR will get merge.

2024-11-08 10:59 UTC, ashishkumar-webkul commented
**Checked the text Field**

1. After selecting the text field facing NaN issue -> https://prnt.sc/Q6NMF9zI05lF

2. Facing product saving issue.

-> https://prnt.sc/Q6NMF9zI05lF

**Screenshots**

![Screenshot from 2024-11-08 16-28-41](https://github.com/user-attachments/assets/b07ad7e9-b8bb-4d46-a0b8-8674771c8a3e)


![Screenshot from 2024-11-08 11-54-12](https://github.com/user-attachments/assets/f494fcb7-fb5e-41d6-96c7-d2690f305711)

![Screenshot from 2024-11-08 11-54-15](https://github.com/user-attachments/assets/80367dd2-6e29-4623-830a-ef4ac17c2d9c)

2024-11-08 11:34 UTC, devansh-webkul commented
> **Checked the text Field**
> 
> 1. After selecting the text field facing NaN issue -> https://prnt.sc/Q6NMF9zI05lF
> 2. Facing product saving issue.
> 
> -> https://prnt.sc/Q6NMF9zI05lF
> 
> **Screenshots**
> 
> ![Screenshot from 2024-11-08 16-28-41](https://private-user-images.githubusercontent.com/92721837/384341941-b07ad7e9-b8bb-4d46-a0b8-8674771c8a3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjQzNzcsIm5iZiI6MTczMTA2NDA3NywicGF0aCI6Ii85MjcyMTgzNy8zODQzNDE5NDEtYjA3YWQ3ZTktYjhiYi00ZDQ2LWEwYjgtODY3NDc3MWM4YTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDExMDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYjhjZGNiZjU2MWI2ZDI1YTEzYmQ1NWU5NDFiYmYwZDYwNGUyMGRmNTFjMTNiNmUxOGFlOTVhNTMyMzI0OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UeSFNQdEQWmhDr8IX7EHVFg3FFhCkjUPc2h-nnxvXgs)
> 
> ![Screenshot from 2024-11-08 11-54-12](https://private-user-images.githubusercontent.com/92721837/384341730-f494fcb7-fb5e-41d6-96c7-d2690f305711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjQzNzcsIm5iZiI6MTczMTA2NDA3NywicGF0aCI6Ii85MjcyMTgzNy8zODQzNDE3MzAtZjQ5NGZjYjctZmI1ZS00MWQ2LTk2YzctZDI2OTBmMzA1NzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDExMDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MDU5ZDdmMGFkN2Y5YWVhMmE5NmMzOGE4OWQ2ZjM0YjE1NjFlODk2MDg1ZDBiOGViYjE2MDM4ZDBhNGY5MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dvWhtsUag_6OIepYPK3J7wdWjVkRUc2wJwvUKddrF7E)
> 
> ![Screenshot from 2024-11-08 11-54-15](https://private-user-images.githubusercontent.com/92721837/384341748-80367dd2-6e29-4623-830a-ef4ac17c2d9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjQzNzcsIm5iZiI6MTczMTA2NDA3NywicGF0aCI6Ii85MjcyMTgzNy8zODQzNDE3NDgtODAzNjdkZDItNmUyOS00NjIzLTgzMGEtZWY0YWMxN2MyZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDExMDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZGQ4NWZmYmUxODI3YWU3YTRmOGMyMGU1YmY3ZTU3MDZmOGIwYTA2YTNhMDA2MmU5ZDgxNTI1N2FkMzdmZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wnbxDCHyKntEygASn8hpyJFQc9QaQpK36TVQtD3hayc)

Fixed the mentioned changes.

2024-12-02 04:20 UTC, ashishkumar-webkul commented
> > **Checked the text Field**
> > 
> > 1. After selecting the text field facing NaN issue -> https://prnt.sc/Q6NMF9zI05lF
> > 2. Facing product saving issue.
> > 
> > -> https://prnt.sc/Q6NMF9zI05lF
> > **Screenshots**
> > ![Screenshot from 2024-11-08 16-28-41](https://private-user-images.githubusercontent.com/92721837/384341941-b07ad7e9-b8bb-4d46-a0b8-8674771c8a3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjQzNzcsIm5iZiI6MTczMTA2NDA3NywicGF0aCI6Ii85MjcyMTgzNy8zODQzNDE5NDEtYjA3YWQ3ZTktYjhiYi00ZDQ2LWEwYjgtODY3NDc3MWM4YTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDExMDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYjhjZGNiZjU2MWI2ZDI1YTEzYmQ1NWU5NDFiYmYwZDYwNGUyMGRmNTFjMTNiNmUxOGFlOTVhNTMyMzI0OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UeSFNQdEQWmhDr8IX7EHVFg3FFhCkjUPc2h-nnxvXgs)
> > ![Screenshot from 2024-11-08 11-54-12](https://private-user-images.githubusercontent.com/92721837/384341730-f494fcb7-fb5e-41d6-96c7-d2690f305711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjQzNzcsIm5iZiI6MTczMTA2NDA3NywicGF0aCI6Ii85MjcyMTgzNy8zODQzNDE3MzAtZjQ5NGZjYjctZmI1ZS00MWQ2LTk2YzctZDI2OTBmMzA1NzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDExMDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MDU5ZDdmMGFkN2Y5YWVhMmE5NmMzOGE4OWQ2ZjM0YjE1NjFlODk2MDg1ZDBiOGViYjE2MDM4ZDBhNGY5MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dvWhtsUag_6OIepYPK3J7wdWjVkRUc2wJwvUKddrF7E)
> > ![Screenshot from 2024-11-08 11-54-15](https://private-user-images.githubusercontent.com/92721837/384341748-80367dd2-6e29-4623-830a-ef4ac17c2d9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNjQzNzcsIm5iZiI6MTczMTA2NDA3NywicGF0aCI6Ii85MjcyMTgzNy8zODQzNDE3NDgtODAzNjdkZDItNmUyOS00NjIzLTgzMGEtZWY0YWMxN2MyZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDExMDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZGQ4NWZmYmUxODI3YWU3YTRmOGMyMGU1YmY3ZTU3MDZmOGIwYTA2YTNhMDA2MmU5ZDgxNTI1N2FkMzdmZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wnbxDCHyKntEygASn8hpyJFQc9QaQpK36TVQtD3hayc)
> 
> Fixed the mentioned changes.


Checked and Found that the issue has been fixed and working fine now.

1. NaN issue has been fixed -> https://prnt.sc/vkfC8cLdPEn_
2. Product Saving issue has been fixed -> https://prnt.sc/3-QR9jDr_PLr
3.  No Console errors are appearing in Shop Front Now.

![Screenshot from 2024-12-02 09-49-02](https://github.com/user-attachments/assets/bdb834b3-4093-466e-b7c3-fa1c920fa8da)
![Screenshot from 2024-12-02 09-49-08](https://github.com/user-attachments/assets/e952a10c-e078-4f65-8baf-f9bdb21eda3e)
![Screenshot from 2024-12-02 09-49-11](https://github.com/user-attachments/assets/c135434a-8eeb-4065-9cd7-14a42ace3129)

2024-12-02 04:36 UTC, ashishkumar-webkul commented
1. Customizable Option -> Text Type -> Price 

There when am adding Alphabet, Alphanumeric Value or Symbol and saving the option -> NaN is appearing.

**Note ->** I haven't saved the product. When producti is save price for customizable option is  appearing 0 which is working fine.

**Issue Screenshots**

https://prnt.sc/aziZciyKYgmY
https://prnt.sc/Uv6mAEcOdUPl

2024-12-02 04:49 UTC, ashishkumar-webkul commented
Suggestion -> If message is not added to Text Field in Shop Front then the details related to Option Name in Main Cart and Mini Cart must not appear.

https://prnt.sc/ARwe2Jp4i2nt

2024-12-02 05:08 UTC, ashishkumar-webkul commented
Enhancement -> Price can have an option for Price Type like Fixed/Percentage.

Reference -> https://prnt.sc/2b2p6Uys60kP

2024-12-02 06:29 UTC, ashishkumar-webkul commented
Checkbox Type
_______________

1. Option Validation message must appear according to the Option Title.

https://prnt.sc/XEiPpWLrWy3Y

2024-12-02 06:51 UTC, ashishkumar-webkul commented
**Radio Type**
_______________

1. Option Validation message must appear according to the Option Title.

https://prnt.sc/KvmQlUOMIcp-

2024-12-02 07:38 UTC, ashishkumar-webkul commented
**Improvement**

In the Customizable Option Type dropdown, the first entry must appear by default. Currently, "Select" is displayed instead, but it should show the first text option.

**Video**

https://github.com/user-attachments/assets/aa651268-118e-4ced-a15a-0eaa7f1a9ea4

2024-12-02 07:46 UTC, ashishkumar-webkul commented
**Select Type**
_______________

1. Undefined Array Key 0 warning message is appearing when we create a non Mandatory Select Option. 
Now go to Shop Front and select none and see the warning message.

**Screenshot ->  https://prnt.sc/Pcys4zAckPKy**

2024-12-02 07:56 UTC, ashishkumar-webkul commented
**Enhancement** 

When adding an amount in the Customizable Option, the Mini Cart and Main Cart should display the price applied to the main price. Currently, only the total calculation is visible, and the applied price is not shown. Please refer to the screenshots below.

https://prnt.sc/HskgMPl0ZwWq

https://prnt.sc/7w92pLr_IbQb

2024-12-02 08:08 UTC, ashishkumar-webkul commented
**Multiselect**
______

1. In a non-mandatory Multiselect option, if no option is selected, the details related to the Multiselect option should not appear.

https://prnt.sc/SPkMhqM5ElUK

2024-12-02 08:30 UTC, ashishkumar-webkul commented
**Date**
______

1. We are able to set previous dates and can checkout product.

https://prnt.sc/D-2TegAFikhq

2024-12-02 12:12 UTC, ashishkumar-webkul commented
**File**
_____________

1. Suggestion -> Please add a note for the extensions which are supported.

SS for Action to be done -> https://prnt.sc/2WxBTwhNVxxP

2024-12-03 07:43 UTC, ashishkumar-webkul commented
File 
___________

When we click on the text or outside the upload button, the file upload selection box appears.

https://github.com/user-attachments/assets/ee7d4414-bf34-4609-8464-359c4b4c8e93

2024-12-03 09:49 UTC, ashishkumar-webkul commented
**All Locale Test Except English**
_____________________

1. Text Type
Add input in text box in Arabic locale. See the result.

https://prnt.sc/Q85yQm79cdfr

2. Text Area Type
Add input in text box in Arabic locale. See the result.

https://prnt.sc/v4Hc9TvCcpaN

3.  Checkbox Type
Select the checkbox options and there we can see the issue

https://prnt.sc/7daov3pAIVf4

4. Radio Type
Select the Radio Options

https://prnt.sc/TYcJWRJLwE_7

5.  Select Type
Select the  options 

https://prnt.sc/bnSc48zsaNui

6. MultiSelect Type
Select the multiselect options.

https://prnt.sc/f7ySXeZ1G56O

7. Date Option
Select the Date 

https://prnt.sc/ImURlPynDE18

8. Time Option
Select the time frame

https://prnt.sc/aHOxEry0S_K5

9. Date and Time Option
Select the Date and Time 

https://prnt.sc/jwGXOLrNFx53

10. File Option
Upload a file.

https://prnt.sc/QBb1HJ_CoItb

2024-12-03 10:11 UTC, ashishkumar-webkul commented
Checked Create Order and Reorder and found Critical issue.

**Create Order**

Add Custom Order product in Create order in Admin and see the console error. 

![Screenshot from 2024-12-03 15-22-50](https://github.com/user-attachments/assets/8072e87a-d932-49c6-9e38-8be578d14681)

![Screenshot from 2024-12-03 15-22-21](https://github.com/user-attachments/assets/08fb7bfe-dade-4950-b381-c0e1163c11f6)

**Reorder**

Purchase a product without custom order and then go to Admin -> Sales -> Orders -> View -> Reorder -> Add Customizable product in it,

![Screenshot from 2024-12-03 15-22-17](https://github.com/user-attachments/assets/8a52cd92-5b3f-4ac7-9487-a9d84d6abb8e)

![Screenshot from 2024-12-03 15-22-21](https://github.com/user-attachments/assets/4e9fda6a-ecdc-4607-b168-2f1561637480)

2024-12-03 10:14 UTC, ashishkumar-webkul requested changes
@devansh-webkul sir I have completed the testing of the PR and I found some issues in it,

**Testing Summary:**  

1. **Custom Options:**  
   - All types of custom options have been tested.  
   - Multiple issues were found and have already been reported.  

2. **Product Details:**  
   - Bundle, Grouped, Downloadable, and Configurable products are not displaying customizable options correctly.  

3. **Pricing:**  
   - Tested actual price, special price, and customer group-specific pricing.  

4. **Custom Product Options:**  
   - There are some doubts regarding three custom options: Time, Date, and Date-Time.  

5. **Product Types:**  
   - All product types have been verified.  

6. **Localization:**  
   - Testing was performed across multiple locales.  
   
7. **Re-order and Create Order from Admin**
  - Testing performed and Found Critical issue.   

**Next Steps:**  
Please address the identified issues. Once resolved, I will conduct a thorough review and retest all points.

2024-12-20 03:43 UTC, ashishkumar-webkul commented
> 1. Customizable Option -> Text Type/ Text Area  -> Price
> 
> There when am adding Alphabet, Alphanumeric Value or Symbol and saving the option -> NaN is appearing.
> 
> **Note ->** I haven't saved the product. When producti is save price for customizable option is appearing 0 which is working fine.
> 
> **Issue Screenshots**
> 
> https://prnt.sc/aziZciyKYgmY https://prnt.sc/Uv6mAEcOdUPl

Checked and found that the issue has been fixed.

Issue Fixed Price Validation.

Text Type -> https://prnt.sc/VcYBOIvBjBRh
Text Area -> https://prnt.sc/NIu0pJ-gr-ay

2024-12-20 10:39 UTC, ashishkumar-webkul commented
> Suggestion -> If message is not added to Text Field/ Text Area in Shop Front then the details related to Option Name in Main Cart and Mini Cart must not appear.
> 
> https://prnt.sc/ARwe2Jp4i2nt
> 
> Suggestion -> We can also add Character Validation in the Text Field/ Text Area to Avoid long text content.
> 
> https://prnt.sc/tobSdr_a3aF7
> 
> Reference -> https://prnt.sc/zBi4z8mUeyrj

Checked and found that the issue has been fixed.

Text Type

https://prnt.sc/8xDVyH8TRMfp
https://prnt.sc/lHfuGrag48bY
https://prnt.sc/IoLm38W1ptV9

Text Area Type

https://prnt.sc/oRw_oC6bvLI2
https://prnt.sc/1-MhjDWQ_IMT
https://prnt.sc/RN9b7Vb9AJsy

2024-12-20 11:50 UTC, ashishkumar-webkul commented
> **Checkbox Type**
> 
> 1. Option Validation message must appear according to the Option Title.
> 
> https://prnt.sc/XEiPpWLrWy3Y

Checked and Found that the issue has been fixed -> https://prnt.sc/Watmcc-71IC3

2024-12-20 13:07 UTC, ashishkumar-webkul commented
> **Radio Type**
> 
> 1. Option Validation message must appear according to the Option Title.
> 
> https://prnt.sc/KvmQlUOMIcp-
> 
> 2. Undefined Array Key 0 warning message is appearing when we create a non Mandatory Radio Option.
>    Now go to Shop Front and select none and see the warning message.
> 
> **Video**
> 
>  Undefined.mp4

Checked and Found issue is still appearing when we do not select none in Radio options if its a non mandatory field and adding the product to cart.

https://prnt.sc/Xa75lV1Q4GxQ

Issue Image -> https://prnt.sc/XnFI76SJFbWd

2024-12-26 11:55 UTC, ashishkumar-webkul commented
> **Select Type**
> 
> 1. Undefined Array Key 0 warning message is appearing when we create a non Mandatory Select Option.
>    Now go to Shop Front and select none and see the warning message.
> 
> **Screenshot -> https://prnt.sc/Pcys4zAckPKy**
> 
> 2. Option Validation message must appear according to the Option Title.
> 
> Screenshot -> https://prnt.sc/u7DC18Eztpko
> 
> Solution -> First Option of the Mandatory Select Option must appear by deafult.

Checked and found one issue is fixed and  other is still remaining.

Issue fixed -> https://prnt.sc/lzMO4QD_iyn6

Issue Not Fixed -> https://prnt.sc/UMryVRnR359l
Still first option is not appearing

2024-12-26 12:01 UTC, ashishkumar-webkul commented
> https://prnt.sc/SPkMhqM5ElUK

Checked and Found that the issue has been fixed and working fine now, Please check the screenshot -> https://prnt.sc/9Z6jyHO_pR0B

2024-12-26 12:24 UTC, ashishkumar-webkul commented
> 3\. I have not selected Time non-mandatory option, Still in cart the amount is added.

1. We are able to set previous dates and can checkout product. -> https://prnt.sc/D-2TegAFikhq
Resolution -> As per the discussion with Devansh Sir, the date can be selected for both future and past days starting from today. No validation can be applied in this regard.

2. I have not selected Date Time non-mandatory option, Still in cart the amount is added.
Issue fixed, Please check the video for reference.

https://github.com/user-attachments/assets/76904a35-aa25-4669-ad1f-0c23d682f335

3. Time Non Mandatory Price issue has been fixed.
Issue fixed -> https://prnt.sc/G15BPyTtaorX

2024-12-26 12:55 UTC, ashishkumar-webkul commented
> **All Locale Test Except English**
> 
> 1. Text Type
>    Add input in text box in Arabic locale. See the result.
> 
> https://prnt.sc/Q85yQm79cdfr
> 
> 2. Text Area Type
>    Add input in text box in Arabic locale. See the result.
> 
> https://prnt.sc/v4Hc9TvCcpaN
> 
> 3. Checkbox Type
>    Select the checkbox options and there we can see the issue
> 
> https://prnt.sc/7daov3pAIVf4
> 
> 4. Radio Type
>    Select the Radio Options
> 
> https://prnt.sc/TYcJWRJLwE_7
> 
> 5. Select Type
>    Select the  options
> 
> https://prnt.sc/bnSc48zsaNui
> 
> 6. MultiSelect Type
>    Select the multiselect options.
> 
> https://prnt.sc/f7ySXeZ1G56O
> 
> 7. Date Option
>    Select the Date
> 
> https://prnt.sc/ImURlPynDE18
> 
> 8. Time Option
>    Select the time frame
> 
> https://prnt.sc/aHOxEry0S_K5
> 
> 9. Date and Time Option
>    Select the Date and Time
> 
> https://prnt.sc/jwGXOLrNFx53
> 
> 10. File Option
>     Upload a file.
> 
> https://prnt.sc/QBb1HJ_CoItb

Checked and found that the Multilocate Unwanated warning message issue has been fixed.

**Video**


https://github.com/user-attachments/assets/9f4c410d-02ce-4f06-bdf0-283f646642f1

2024-12-26 12:59 UTC, ashishkumar-webkul commented
> Checked Invoice, Shipment , Create Order and Reorder and found Critical issue.
> 
> **Shipping and Handling**
> 
> Shipping and Handling price is appearing same as Subtotal -> https://img001.prntscr.com/file/img001/U-DwZWBnTJKN5nM3U3X6gg.png
> 
> **Create Order**
> 
> Add Custom Order product in Create order in Admin and see the console error.
> 
> ![Screenshot from 2024-12-03 15-22-50](https://private-user-images.githubusercontent.com/92721837/391917447-8072e87a-d932-49c6-9e38-8be578d14681.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTExOTcsIm5iZiI6MTczNTIxMDg5NywicGF0aCI6Ii85MjcyMTgzNy8zOTE5MTc0NDctODA3MmU4N2EtZDkzMi00OWM2LTllMzgtOGJlNTc4ZDE0NjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDExMDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzNWZlZDhjMDM4NmVhM2U3MjI3YTM1YzljODZlYmIxMDFjNzdjM2U2YjA4ZGJkN2MwMjBhMGI1NmZlOWM1MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Li7ad83801Qtb2xdU4DlC2DNxxV4sIgToqaDsMZcc_4)
> 
> ![Screenshot from 2024-12-03 15-22-21](https://private-user-images.githubusercontent.com/92721837/391917578-08fb7bfe-dade-4950-b381-c0e1163c11f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTExOTcsIm5iZiI6MTczNTIxMDg5NywicGF0aCI6Ii85MjcyMTgzNy8zOTE5MTc1NzgtMDhmYjdiZmUtZGFkZS00OTUwLWIzODEtYzBlMTE2M2MxMWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDExMDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MDEwNWIwYTE3NjdmMTA3YWI0OTBhZDBkZTIyYTBhOTJjMDhmZDMwMWE0NjVjNTQ4ZTA0ZGQwN2FjNWMyOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MEL_AMu1Ee0mIp0D8bsbnw9ZQOgwzeQDKHpLEkIhnUM)
> 
> **Reorder**
> 
> Purchase a product without custom order and then go to Admin -> Sales -> Orders -> View -> Reorder -> Add Customizable product in it,
> 
> ![Screenshot from 2024-12-03 15-22-17](https://private-user-images.githubusercontent.com/92721837/391919080-8a52cd92-5b3f-4ac7-9487-a9d84d6abb8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTExOTcsIm5iZiI6MTczNTIxMDg5NywicGF0aCI6Ii85MjcyMTgzNy8zOTE5MTkwODAtOGE1MmNkOTItNWIzZi00YWM3LTk0ODctYTlkODRkNmFiYjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDExMDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMjM4M2Q3NjY2YmE5ZmM4Zjg2YzVjNDAzOTkwMmMzNGNjZWVhOTc2YjNmNTBhYzc4NTc5ZDdhNGRhODBlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CN9aCyg5yCtue1F_Rg56aOyhQ1kyUSsCGaFimGbVzEQ)
> 
> ![Screenshot from 2024-12-03 15-22-21](https://private-user-images.githubusercontent.com/92721837/391919089-4e9fda6a-ecdc-4607-b168-2f1561637480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTExOTcsIm5iZiI6MTczNTIxMDg5NywicGF0aCI6Ii85MjcyMTgzNy8zOTE5MTkwODktNGU5ZmRhNmEtZWNkYy00NjA3LWIxNjgtMmYxNTYxNjM3NDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDExMDEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZGJmM2U5NTc2NDczOTBlZTA1YWQ0MmY4MTIxNWNkNjU5MjM4YjgyYTRjNDBkMDc1NTFiZTZlZmI2N2ZjZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hYBohGi5Mr112mmpG-exh9XQ-7sQQv2RsctixykIRSw)

Shipping and Handling issue is still appearing

**Video**


https://github.com/user-attachments/assets/028ef75f-80c6-4164-934c-abb49f7dfeb2

2024-12-30 06:19 UTC, ashishkumar-webkul commented
---

@devansh-webkul Sir, 

I have reviewed the PR and, after extensive testing, identified several issues that still persist, some of which are critical. While certain issues have been fixed and are functioning correctly, others are under observation and require further improvements.  

I conducted the testing on a fresh clone of Bagisto's Master Branch, merging the PR before installing Bagisto. Below is a summary of the findings:  

1. **Radio Option:**  
   - Issue: The problem persists when "none" is not selected in radio options for a non-mandatory field while adding the product to the cart.  
   - [Issue Image](https://prnt.sc/XnFI76SJFbWd)

2. **Multiselect Type:**  
   - Issue: Dropdown options are not appearing for mandatory fields. The first option should appear instead of a blank box.  
   - [Issue Not Fixed](https://prnt.sc/UMryVRnR359l)

3. **Shipping and Handling Price:**  
   - Issue: The price remains the same in the order details.  
   - [Screenshot](https://img001.prntscr.com/file/img001/U-DwZWBnTJKN5nM3U3X6gg.png)

4. **Reorder Not Working:**  
   - Issue: Console errors are appearing.  

5. **Admin Create Order Not Working:**  
   - Issue: Console errors are appearing.  

Further testing can proceed once these issues are resolved.  

Thank you.  

---

2025-01-22 13:10 UTC, devansh-webkul commented
All the mentioned issues have been resolved.

2025-01-23 04:18 UTC, ashishkumar-webkul commented
> @devansh-webkul Sir,
> 
> I have reviewed the PR and, after extensive testing, identified several issues that still persist, some of which are critical. While certain issues have been fixed and are functioning correctly, others are under observation and require further improvements.
> 
> I conducted the testing on a fresh clone of Bagisto's Master Branch, merging the PR before installing Bagisto. Below is a summary of the findings:
> 
> 1. **Radio Option:**
>    
>    * Issue: The problem persists when "none" is not selected in radio options for a non-mandatory field while adding the product to the cart.
>    * [Issue Image](https://prnt.sc/XnFI76SJFbWd)
> 2. **Multiselect Type:**
>    
>    * Issue: Dropdown options are not appearing for mandatory fields. The first option should appear instead of a blank box.
>    * [Issue Not Fixed](https://prnt.sc/UMryVRnR359l)
> 3. **Shipping and Handling Price:**
>    
>    * Issue: The price remains the same in the order details.
>    * [Screenshot](https://img001.prntscr.com/file/img001/U-DwZWBnTJKN5nM3U3X6gg.png)
> 4. **Reorder Not Working:**
>    
>    * Issue: Console errors are appearing.
> 5. **Admin Create Order Not Working:**
>    
>    * Issue: Console errors are appearing.
> 
> Further testing can proceed once these issues are resolved.
> 
> Thank you.

1. Radio Button Issue

Checked and found that the issue has been fixed and working fine.
Screenshot -> https://prnt.sc/v-8FgyLF7_-j , https://prnt.sc/JOf7aWimtl5g


2. Multiselect Type

Checked and found that the issue has been fixed and working fine.
Screenshot -> https://prnt.sc/YSATbGBjVN-D

3. Shipping and Handling Price Issue.

This issue was appearing from core and hence this will be fixed directly over there.
Issue reference -> https://github.com/bagisto/bagisto/issues/10475

4. Reorder and Create Order From Admin

Select Type Product -> Checked and Found Working fine.
Screenshot -> https://prnt.sc/RfVS8W9mOPX5

Simple Product Text Area Type -> Checked and Found Working Fine.
Screenshot -> https://prnt.sc/6XwqPqCY-FVg

Simple Product Checkbox Type -> Checked and Found Working Fine.
Screenshot -> https://prnt.sc/9yrN4ntyEhn8

Simple Product Radio Type -> Checked and Found Working Fine.
Screenshot -> https://prnt.sc/v5bLHS2C3Eyh

Simple Product Select Type -> Checked and Found Working Fine.
Screenshot -> https://prnt.sc/feOHRDdblR3W

Simple Product Multiselect Type -> Checked and Found Working Fine.
Screenshot -> https://prnt.sc/K_I4JTRYAEFr

Simple Product Date Type -> Checked and Found Working Fine.
Screenshot -> https://prnt.sc/aYu7pDbuoK-M

Simple Product Date & Time Type -> Checked and Found Working Fine.
Screenshot -> https://prnt.sc/1ovTxcMK9CoO

Simple Product Time Type -> Checked and Found Working Fine.
Screenshot -> https://prnt.sc/GA5QeB-yyua1

Simple Product File Type -> Checked and Found Working Fine.
Screenshot -> https://prnt.sc/RDeROu3Wwkxj

@devansh-webkul 

I have checked  and verified all the issues and hence this PR is completed and I am approving the PR.

2025-01-23 04:41 UTC, merged