add label color to status column
bagisto/bagisto pull request #10391
Opened 2024-12-09 10:46 UTC by phyothiha

## Issue Reference
#10387

2024-12-13 06:15 UTC, amit-webkul requested changes

2024-12-13 06:15 UTC, amit-webkul commented on packages/Webkul/Admin/src/Resources/views/sales/transactions/index.blade.php
> +                                    </template>
We can use `v-else-if` here to optimize the code slightly, and the v-if condition can be added directly to the `<p>` tag for better readability and efficiency.

2024-12-13 07:47 UTC, amit-webkul requested changes

2024-12-13 07:47 UTC, amit-webkul commented on packages/Webkul/Admin/src/Resources/views/sales/transactions/index.blade.php
> +                                        @lang('admin::app.sales.transactions.index.datagrid.completed')
When a tag contains two or more attributes, we should separate each attribute onto a new line for better readability.

You can refer to the example code snippet below:

```
<p
    v-if="data.invoice_id"
    class="text-gray-600 dark:text-gray-300"
    v-text="data.invoice_id"
>
</p>
```

2024-12-13 08:30 UTC, amit-webkul requested changes

2024-12-13 08:30 UTC, amit-webkul commented on packages/Webkul/Admin/src/Resources/views/sales/transactions/index.blade.php
> +                                    <p
Could you please remove the extra space before the <p> tag?

2024-12-17 06:37 UTC, devansh-webkul commented
We will do this internally.

2024-12-17 06:37 UTC, closed without merging