fix typo in customer profile update
bagisto/bagisto pull request #3986
Opened 2020-10-01 10:52 UTC by bitasterisk

Typo in customer profile update.

2020-10-01 11:55 UTC, ghermans requested changes

2020-10-01 12:33 UTC, bitasterisk commented on packages/Webkul/API/Http/Controllers/Shop/SessionController.php
> +            'message' => 'Your account has been updated successfully.',
okay. lets create a language file for https://devdocs.bagisto.com/api_customer.html.

2020-10-07 07:52 UTC, ghermans requested changes
Translations should be added to the package folder ´Webkul/API´  instead of your bagisto root.

2020-10-30 11:36 UTC, vaishaliwebkul commented
@bitasterisk 
No response from last 23 days so closing this PR

2020-10-30 11:36 UTC, closed without merging