Issue #3975 Fixed
bagisto/bagisto pull request #3997
Opened 2020-10-05 07:04 UTC by vishal-webkul

Issue: #3975

2020-10-07 08:02 UTC, bhanu-webkul commented
done

2020-10-08 06:25 UTC, rahulcs0082 requested changes
Hi @vishal-webkul 

So much extra space is added, kindly check and fix it accordingly.

2020-10-08 06:44 UTC, vishal-webkul commented
Hi @rahulcs0082 
extra space removed

2020-10-30 09:35 UTC, ghermans approved these changes

2020-10-30 09:36 UTC, merged