Fixed Responsive issue  #3929
bagisto/bagisto pull request #4059
Opened 2020-10-09 14:04 UTC by deepaksinghgusain227

Fixed Responsive issue  #3929

2020-10-09 14:07 UTC, ghermans requested changes

2020-10-09 14:07 UTC, ghermans commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +        background-color: #fff;
Please use $white-color as defined in _variables.scss

2020-10-12 09:56 UTC, ghermans approved these changes

2020-10-20 12:21 UTC, deepaksinghgusain227 commented
closed due to new PR

2020-10-20 12:21 UTC, closed without merging