Hide horizontal scrollbar on the sidebar
bagisto/bagisto pull request #4157
Opened 2020-10-22 05:21 UTC by praem90

layered navigation is showing a single line when increasing the price slider #4111

**BUGS:**

>Hide overflow on the left sidebar wrapper

2020-10-22 06:48 UTC, vaishaliwebkul commented
@praem90 
changes are not coming as compilation files are missing, please run the npm command.

2020-10-22 08:32 UTC, vaishaliwebkul approved these changes

2020-10-22 09:01 UTC, jitendra-webkul commented
Resolve conflicts

2020-10-30 14:13 UTC, ghermans requested changes
@praem90 can you please resolve the current conflicts?

2020-10-30 14:47 UTC, merged