Fixed minimum order amount should also accept the minimum value #4262
bagisto/bagisto pull request #4263
Opened 2020-11-16 12:57 UTC by devansh-webkul

**BUGS:**
Link: https://github.com/bagisto/bagisto/issues/4262

2020-11-16 13:00 UTC, shubhwebkul requested changes
You can create a generic method to check the amount.

2020-11-16 14:29 UTC, vaishaliwebkul commented
@devansh-webkul 
I think we should also update the alert message with currency symbol likewise "Minimum order amount is $500.00"

2020-11-17 09:27 UTC, vaishaliwebkul approved these changes

2020-11-17 09:55 UTC, shubhwebkul approved these changes

2020-11-17 10:15 UTC, vaishaliwebkul approved these changes

2020-11-17 11:01 UTC, merged