Added condition that allow to use repository in console mode
bagisto/bagisto pull request #4489
Opened 2021-01-15 13:06 UTC by k3rnel

**BUGS:**

>Please describe the issue that you solved if its not filed.

Fixed error when trying to use update method in console mode.

2021-01-25 09:28 UTC, k3rnel commented
Cmon guys, 10 days one condition

2021-01-25 10:55 UTC, devansh-webkul commented
Hi @k3rnel,

Can you show me a screenshot of the error?

Because there are 4 more types also and one abstract class as well. So concerned is not related to the configurable product.

2021-01-25 12:40 UTC, k3rnel commented
Okay I found a solution. Where can I define some function, that we can use in entire application?

2021-01-25 12:55 UTC, devansh-webkul commented
Hi @k3rnel,

First of all, I want to know what error are you facing and the steps to reproduce that error.

And the second one is for the product changes you need to review all the classes in this path `packages/Webkul/Product/src/Type`.

The main class is `AbstractType` as this class is inherited to all types and some methods are overridden as well.

2021-01-25 13:24 UTC, k3rnel commented
Create some artisan command and try to use ProductRepository in there. Try to update some configurable product. In my case its seems like this:

```php
/** @var \Webkul\Product\Models\Product $product */
  $product = $this->productRepository->create([
      'type'                => 'configurable',
      'attribute_family_id' => $attributeFamily->id,
      'sku'                 => $sku,
      'super_attributes'    => $superAttributes,
      'family'              => $attributeFamily->id,
  ]);
```
```php
$this->productRepository->update([
      'channel'           => 'Store',
      'name'              => $name,
      'url_key'           => Str::slug($name),
      'status'            => '1',
      'guest_checkout'    => '1',
      'short_description' => '<p>'.$this->faker->text(150).'</p>',
      'description'       => '<p>'.$this->faker->text(500).'</p>',
      'images'            => [
            'image_1' => ''
      ],
      'meta_title'        => '',
      'meta_keywords'     => '',
      'meta_description'  => '',
      'locale'            => 'en',
      'channels'          => $channels->pluck('id')->toArray(),
      'variants'          => $this->prepareVariantsData($product)
], $product->id);
```
![using request in non-request env](https://user-images.githubusercontent.com/44973047/105711493-0e6d9c00-5f32-11eb-95c9-c9f14cc4a249.png)

2021-01-25 13:55 UTC, devansh-webkul requested changes

2021-01-25 13:55 UTC, devansh-webkul commented on packages/Webkul/Product/src/Type/Configurable.php
> +        if (app()->runningInConsole() || request()->route()->getName() != 'admin.catalog.products.massupdate') {
There is no need for this check, just try with this,

~~~php
$route = request()->route() ? request()->route()->getName() : '';
~~~

Take a reference from `AbstractType` class.

2021-01-25 14:09 UTC, devansh-webkul requested changes
There are some changes needed and also update this class also,

- [x] packages/Webkul/Product/src/Type/Bundle.php's update method
- [x] packages/Webkul/Product/src/Type/Downloadable.php's update method
- [x] packages/Webkul/Product/src/Type/Grouped.php's update method

2021-01-25 14:09 UTC, devansh-webkul commented on packages/Webkul/Product/src/Type/Configurable.php
> +        if (!request()->route() || request()->route()->getName() != 'admin.catalog.products.massupdate') {
Not like that, check this,
https://github.com/bagisto/bagisto/blob/2b4ca622b43910536b8441fce6a5e5f66a221774/packages/Webkul/Product/src/Type/AbstractType.php#L212

~~~php
$route = request()->route() ? request()->route()->getName() : "";

if ($route !== 'admin.catalog.products.massupdate') {
~~~

2021-01-25 14:15 UTC, k3rnel commented
I did what you said. But for the future, we need to implement the most universal way to solve all the problems associated with checking the name of the route. Or I can create another pull request for this. Can you just tell me where I can deploy some function/method that I can use in all packages

2021-01-25 14:19 UTC, k3rnel commented
> There are some changes needed and also update this class also,
> 
> * [ ]  packages/Webkul/Product/src/Type/Bundle.php's update method
> * [ ]  packages/Webkul/Product/src/Type/Downloadable.php's update method
> * [ ]  packages/Webkul/Product/src/Type/Grouped.php's update method

Okay

2021-01-25 14:26 UTC, devansh-webkul commented
> I did what you said. But for the future, we need to implement the most universal way to solve all the problems associated with checking the name of the route. Or I can create another pull request for this. Can you just tell me where I can deploy some function/method that I can use in all packages?

Well, this not necessarily needed because everywhere it's already handled. Because it obvious in the terminal you always get null.

2021-01-25 17:03 UTC, devansh-webkul commented
Hi @k3rnel,

Just one last thing, update your branch with the master as it is 46 commits behind.

2021-01-26 08:26 UTC, k3rnel commented
Hi @devansh-webkul ,

Merged :)

2021-01-27 04:10 UTC, devansh-webkul approved these changes

2021-01-27 04:49 UTC, merged