replaced product image and product video helper with facades
bagisto/bagisto pull request #4550
Opened 2021-02-04 11:16 UTC by prateek-webkul

2021-02-04 13:18 UTC, rahulshukla-webkul requested changes
Hi @prateek-webkul 

Kindly create helpers for each facades.

2021-02-04 13:36 UTC, prateek-webkul commented
> Hi @prateek-webkul
> 
> Kindly create helpers for each facades.

Implemented

2021-02-04 13:52 UTC, rahulshukla-webkul commented on packages/Webkul/Product/src/Providers/ProductServiceProvider.php
> +        $loader = AliasLoader::getInstance();
No need to declare $loader two times.

2021-02-04 13:58 UTC, prateek-webkul commented on packages/Webkul/Product/src/Providers/ProductServiceProvider.php
> +        $loader = AliasLoader::getInstance();
removed another one

2021-02-05 06:51 UTC, rahulshukla-webkul approved these changes

2021-02-05 12:49 UTC, merged