Enhancement #3477, images for variant product
bagisto/bagisto pull request #4717
Opened 2021-03-09 09:46 UTC by rahulshukla-webkul

Enhancement #3477, images for variant product.

2021-03-11 11:52 UTC, vaishaliwebkul commented
@rahulshukla-webkul 
the size of the variant images should be small so that the UI should be fixed https://prnt.sc/10it9h4

2021-03-11 15:14 UTC, vaishaliwebkul commented
@ghermans would be helpful if you could check the changes added with this PR and provide suggestions on it whether this PR is helpful or not? as I am quite confused

2021-03-16 14:14 UTC, ghermans requested changes
@rahulshukla-webkul i believe @vaishaliwebkul feedback is to make the image size smaller in the table

2021-03-19 09:07 UTC, ghermans commented on packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
> +                        <label class="image-item" v-bind:class="{ 'has-image': imageData[index] }" style="height: 100px; width: 100px; background-size: 100px 100px;">
@rahulshukla-webkul is there a specific reason why css code is added here instead of using the scss files?

2021-03-19 09:55 UTC, ghermans approved these changes

2021-03-19 09:58 UTC, merged