Enhancement Completed Responsive Admin #4295
bagisto/bagisto pull request #4721
Opened 2021-03-11 07:07 UTC by devansh-webkul

## Enhancement
Link: https://github.com/bagisto/bagisto/issues/4295

2021-03-11 14:28 UTC, ghermans requested changes

2021-03-11 14:28 UTC, ghermans commented on packages/Webkul/Ui/src/Resources/assets/sass/app.scss
>                      color: #333333;
Static color is defined, please use the color vars

2021-03-11 14:28 UTC, ghermans commented on packages/Webkul/Ui/src/Resources/assets/sass/app.scss
>          color: #8E8E8E;
Static color is defined, please use the color vars

2021-03-12 05:27 UTC, devansh-webkul commented
Hi @ghermans,

I have added all the necessary variables which have been used multiple times.

2021-03-12 12:49 UTC, merged