Captcha Integrated #4632
bagisto/bagisto pull request #4970
Opened 2021-06-25 13:56 UTC by devansh-webkul

## Description
Link: https://github.com/bagisto/bagisto/issues/4632

## How To Test This?
... will add

2021-06-26 01:33 UTC, ghermans requested changes
Updated dutch translations are missing for packages/Webkul/Customer

2021-07-01 07:26 UTC, vaishaliwebkul commented
@devansh-webkul 

- [ ] Captcha is mandatory so when submit form without selecting captcha warning should be visible instead of reloading the page for eg; https://prnt.sc/17t0m9y
- [ ] Forgot password captcha should be added

2021-07-02 05:54 UTC, devansh-webkul commented
Hi @vaishaliwebkul,

Mentioned changes have been done.

2021-07-02 10:49 UTC, vaishaliwebkul approved these changes

2021-07-02 10:51 UTC, merged