Guest Checkout sucess add register #4356
bagisto/bagisto pull request #5276
Opened 2021-10-26 19:32 UTC by domko17

## Issue Reference

#4356 
## Description

## How To Test This?

## Documentation
- [ ] My pull request requires an update on the documentation repository.

2021-11-03 04:35 UTC, devansh-webkul requested changes

2021-11-03 04:35 UTC, devansh-webkul commented on packages/Webkul/Customer/src/Http/Controllers/RegistrationController.php
> +            Order::where('customer_email', $customer->email)->update(['customer_id' => $customer->id]);
1 line between 182 and 183.

2021-11-03 08:19 UTC, domko17 commented on packages/Webkul/Customer/src/Http/Controllers/RegistrationController.php
> +            Order::where('customer_email', $customer->email)->update(['customer_id' => $customer->id]);
what? something is wrong ?

2021-11-03 08:21 UTC, devansh-webkul commented on packages/Webkul/Customer/src/Http/Controllers/RegistrationController.php
> +            Order::where('customer_email', $customer->email)->update(['customer_id' => $customer->id]);
Add line here.

2021-11-03 15:19 UTC, domko17 commented on packages/Webkul/Customer/src/Http/Controllers/RegistrationController.php
> +            Order::where('customer_email', $customer->email)->update(['customer_id' => $customer->id]);
its done

2021-11-04 18:44 UTC, ghermans approved these changes

2021-11-04 18:44 UTC, merged