fix admin menu does not appear in rtl langs
bagisto/bagisto pull request #5343
Opened 2021-11-19 16:35 UTC by AmooAti

## Issue Reference
Link: #5342 

## Description

## How To Test This?

## Documentation
- [ ] My pull request requires an update on the documentation repository.

2021-11-22 05:48 UTC, devansh-webkul commented
Hi @AmooAti,

I just tested your pull request, one issue found to have a look,

![Screenshot](https://user-images.githubusercontent.com/68321766/142807405-7599f355-c109-4ec2-b5a8-bef8f1f51c2e.png)

I think the arrow should be outside.

2021-11-22 11:39 UTC, devansh-webkul commented
It reproducible just toggle the button.

2021-11-22 14:32 UTC, AmooAti commented
Hi @devansh-webkul,
I fixed the issue that you mentioned also if found another issue with closing and opening side nav and the space that content-wrapper can have, also change the direction of arrows.
but I think my code is not optimum and it can be better in nav-slide-button component (two style classes and two if conditions)

2021-11-23 04:58 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/assets/js/components/navigation/nav-slide-button.vue
> +                }
I think instead of adding extra prop, value can be unset from the scss file as well. If you write unset in the rtl file.

2021-11-23 05:00 UTC, devansh-webkul requested changes

2021-11-23 05:00 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/layouts/nav-aside.blade.php
> +    <nav-slide-button  @if (core()->getCurrentLocale() && core()->getCurrentLocale()->direction == 'rtl') icon-class="accordian-right-icon" :direction="'rtl'" @else icon-class="accordian-left-icon" @
When language changes body tag always have `.rtl` class, you just need to write the classes in the `packages/Webkul/Velocity/src/Resources/assets/sass/components/rtl.scss`.

2021-11-23 05:00 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/layouts/nav-left.blade.php
> +    <nav-slide-button id="nav-expand-button" style="display: none;" @if (core()->getCurrentLocale() && core()->getCurrentLocale()->direction == 'rtl') icon-class="accordian-left-icon" :direction="'rt
Same here.

2021-11-23 05:02 UTC, devansh-webkul commented
Hi @AmooAti,

Please check the mentioned review.

Although functionality is working fine but in my opinion, this can be done. What's your suggestion?

2021-11-23 11:27 UTC, AmooAti commented
Hi @devansh-webkul,
Thanks, I've made changes and used CSS for all manners, but I have doubts about the active class that I added maybe better to use display hide selector but from another point maybe it will be useful for future customization.

2021-11-23 13:35 UTC, devansh-webkul approved these changes

2021-11-23 13:37 UTC, merged