Issue #6469 fixed
bagisto/bagisto pull request #6470
Opened 2022-06-03 11:37 UTC by Sanjaybhattwebkul

## Issue Reference
#6469
>Translation added catalog configuration

2022-06-04 14:25 UTC, ghermans commented on packages/Webkul/Admin/src/Resources/lang/en/app.php
> +            'allow-no-of-new-product-homepage'      => 'Allowed No. of New Product in Homepage',
Please change this to 'Total number of new products on homepage'

2022-06-04 14:29 UTC, ghermans commented on packages/Webkul/Admin/src/Resources/lang/en/app.php
> +            'allow-no-of-featured-product-homepage' => 'Allowed No. of Featured Product in Homepage',
Please change this to 'Total number of featured products on the homepage'

2022-06-04 14:30 UTC, ghermans requested changes
Please check the following

2022-06-06 05:36 UTC, Sanjaybhattwebkul commented
@ghermans 
Changes **complete**, please **check**

2022-06-12 13:26 UTC, merged