Fixed issue #6458
bagisto/bagisto pull request #6525
Opened 2022-07-06 12:24 UTC by akathuria289

## Issue Reference
#6458

2022-07-07 05:39 UTC, Sanjaybhattwebkul commented
@akathuria289 
The product's **price** can be a **decimal** value. so it is still a bug.
Please find the screenshot [Here](https://prnt.sc/whH2OJLO2RYK)

2022-07-07 11:24 UTC, akathuria289 commented
@Sanjaybhattwebkul Fixed

2022-07-18 06:15 UTC, devansh-webkul requested changes

2022-07-18 06:15 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
> +                            <span class="control-error" v-if="errors.has('value')">@{{ errors.first('value') }}</span>
Use `v-text` here.

2022-07-18 06:15 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
> +                            <input v-validate="matchedAttribute.type == 'price'?'decimal:2':'' || matchedAttribute.type == 'decimal'?'decimal:2':'' || matchedAttribute.type == 'integer' ? 'decimal:2'
Proper spacing.

2022-07-18 07:57 UTC, devansh-webkul approved these changes

2022-07-19 20:11 UTC, merged

2022-07-20 05:13 UTC, jitendra-webkul commented on packages/Webkul/Admin/src/Resources/views/marketing/promotions/catalog-rules/create.blade.php
> +                            <input v-validate="matchedAttribute.type == 'price' ? 'decimal:2' : '' || matchedAttribute.type == 'decimal' ? 'decimal:2' : '' || matchedAttribute.type == 'integer' ? 'de
add space after decimal: