Issue #6471 fixed
bagisto/bagisto pull request #6527
Opened 2022-07-07 05:54 UTC by Sanjaybhattwebkul

## Issue Reference
#6471
> Override  calendar CSS for customer's account page

2022-07-09 10:10 UTC, ghermans requested changes
Please use the scss files instead of pushing the css code from the blade file.

2022-07-23 06:09 UTC, devansh-webkul requested changes

2022-07-23 06:09 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/customers/account/profile/edit.blade.php
> +<style>
Move this to scss and share compiled version as well.

2022-07-25 03:57 UTC, devansh-webkul requested changes
Use SCSS.

2022-08-03 05:52 UTC, closed without merging