Fixed issue #6428
bagisto/bagisto pull request #6528
Opened 2022-07-07 06:58 UTC by akathuria289

## Issue Reference
#6428

## Description
Changed the type of input field from text to number

2022-07-07 11:47 UTC, Sanjaybhattwebkul commented
@akathuria289 
The ordered amount can not be **0.**. the minimum order amount should be greater then **00**

2022-07-11 11:12 UTC, Sanjaybhattwebkul commented
@akathuria289 
Now this is working fine, please find the screenshot [Here](https://prnt.sc/jXNxbOehaL-3)

2022-07-11 11:12 UTC, Sanjaybhattwebkul approved these changes

2022-07-11 11:39 UTC, devansh-webkul requested changes

2022-07-11 11:39 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/configuration/field-type.blade.php
> +            <input type="number" min="1" v-validate="'{{ $validations }}'" class="control" id="{{ $name }}" name="{{ $name }}" value="{{ old($nameKey) ?: core()->getConfigData($nameKey, $channel, $lo
This will impact all field types with numbers on the configuration page. Some of the fields may have zero also.

2022-08-03 06:34 UTC, devansh-webkul approved these changes

2022-08-03 06:40 UTC, jitendra-webkul approved these changes

2022-08-03 06:41 UTC, merged