Percentage discount getting save more than 100 #6554
bagisto/bagisto pull request #6561
Opened 2022-07-13 11:38 UTC by papnoisanjeev

## Issue Reference
#6554

## Description
Percentage discount validation added as previously admin was able to added percentage more than 100.

2022-07-13 12:42 UTC, Sanjaybhattwebkul commented
@papnoisanjeev 
Not working properly, please find the screenshot [Here](https://prnt.sc/imiwP4o_KRnr)

2022-07-13 13:09 UTC, Sanjaybhattwebkul commented
@papnoisanjeev 
The page should focus on the error and the rest should be as it is. if there is any warning message for the percentage amount.

2022-07-18 05:51 UTC, devansh-webkul requested changes
This can be handled from validation no extra code needed,
https://github.com/bagisto/bagisto/blob/a41e7102503214582f1d85ebc844c5509d0002b9/packages/Webkul/CartRule/src/Http/Controllers/CartRuleController.php#L100

2022-07-18 05:51 UTC, devansh-webkul commented on packages/Webkul/CartRule/src/Http/Controllers/CartRuleController.php
> +            if (request()->request->get('action_type') == "by_percent") {
This can be handled from the validation part.

2022-07-18 05:51 UTC, devansh-webkul commented on packages/Webkul/CartRule/src/Http/Controllers/CartRuleController.php
> +            if ($request->request->get('action_type') == "by_percent") {
Same here.

2022-07-18 05:51 UTC, devansh-webkul commented on packages/Webkul/CatalogRule/src/Http/Controllers/CatalogRuleController.php
> +        if (request()->request->get('action_type') == "by_percent") {
Same here.

2022-07-18 05:51 UTC, devansh-webkul commented on packages/Webkul/CatalogRule/src/Http/Controllers/CatalogRuleController.php
> +        if ($request->request->get('action_type') == "by_percent") {
Same here.

2022-07-18 12:40 UTC, closed without merging