Fixed issue #6558
bagisto/bagisto pull request #6571
Opened 2022-07-19 07:13 UTC by akathuria289

## Issue Reference
#6558

## Description
Fixed the CSS of the cross icon on booking product

2022-07-19 07:35 UTC, devansh-webkul requested changes

2022-07-19 07:35 UTC, devansh-webkul commented on packages/Webkul/BookingProduct/src/Resources/assets/sass/velocity.scss
> +                position:relative;
Add one space after the colon.

2022-07-19 10:34 UTC, akathuria289 commented on packages/Webkul/BookingProduct/src/Resources/assets/sass/velocity.scss
> +                position:relative;
Both Added

2022-07-22 04:39 UTC, Sanjaybhattwebkul commented
@akathuria289 
**Not working** for Arabic locale, please find the screenshot [Here](https://prnt.sc/H7qcN4ZzsQtg)

2022-07-23 07:52 UTC, akathuria289 commented
@Sanjaybhattwebkul Fixed

2022-07-23 07:56 UTC, devansh-webkul requested changes

2022-07-23 07:56 UTC, devansh-webkul commented on packages/Webkul/BookingProduct/src/Resources/views/shop/velocity/products/view/booking/slots.blade.php
> +                <div class="form-group date {{$product->locale == 'ar' ? 'rtl' : ''}}" :class="[errors.has('booking[date]') ? 'has-error' : '']">
No need for a case here, as the body tag already has rtl. Handle it from scss in rtl file.

2022-07-23 08:37 UTC, akathuria289 commented
@devansh-webkul Done

2022-07-23 10:21 UTC, closed without merging

2022-07-23 10:22 UTC, Sanjaybhattwebkul commented
New pr created for the same issue : https://github.com/bagisto/bagisto/pull/6595