Fixed issue #6371
bagisto/bagisto pull request #6573
Opened 2022-07-19 09:46 UTC by akathuria289

## Issue Reference
#6371

## Description
Flash messages appear when catalog or cart rule applied

2022-07-22 06:13 UTC, Sanjaybhattwebkul commented
@akathuria289 
Not working properly, The flash message will show only when the cart or catalog rule will be applied.

2022-07-22 07:03 UTC, akathuria289 commented
@Sanjaybhattwebkul It`s working as you can see in the reference video - https://www.awesomescreenshot.com/video/10102502?key=c800170ac36a2cca41e4975edaa167e4

2022-07-23 11:05 UTC, Sanjaybhattwebkul commented
@akathuria289 
Please disable the cart rule and try again to place an order. 
If the cart rule is **disabled** then the flash message **should not be visible.**

2022-07-23 11:47 UTC, akathuria289 commented
@Sanjaybhattwebkul Fixed

2022-07-23 11:57 UTC, Sanjaybhattwebkul approved these changes

2022-07-23 11:57 UTC, Sanjaybhattwebkul commented
@akathuria289 
This is **working fine** please find the screenshot [Here](https://prnt.sc/Ra9N0FSEAG1x)

2022-07-23 12:02 UTC, devansh-webkul requested changes

2022-07-23 12:02 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/lang/en/app.php
> +            'rule-applied'              => 'Cart rule applied',
Add remaining files key.

2022-07-23 12:09 UTC, jitendra-webkul commented on packages/Webkul/Shop/src/Http/Controllers/OnepageController.php
> +        if ($cart->applied_cart_rule_ids != "") {
Use single quotes here

2022-07-23 12:47 UTC, akathuria289 commented
Done @devansh-webkul Sir @jitendra-webkul Sir

2022-07-23 12:52 UTC, devansh-webkul approved these changes

2022-07-23 12:56 UTC, jitendra-webkul approved these changes

2022-07-23 12:56 UTC, merged