Validation for percentage amt for Cart and Catalog Rule.
bagisto/bagisto pull request #6580
Opened 2022-07-20 06:58 UTC by papnoisanjeev

## Issue Reference
#6554

## Description
Added validation for percentage amount for Catalog and Cart Rule and Handled validation using **FormRequest** and removed validation from controller.

2022-07-20 08:13 UTC, devansh-webkul requested changes

2022-07-20 08:13 UTC, devansh-webkul commented on packages/Webkul/CartRule/src/Http/Controllers/CartRuleController.php
>       *
Add PHPDoc also.

2022-07-20 08:13 UTC, devansh-webkul commented on packages/Webkul/CartRule/src/Http/Controllers/CartRuleController.php
> +    public function update(CartRuleRequest $cartRuleRequest, $id)
Same here.

2022-07-20 08:13 UTC, devansh-webkul commented on packages/Webkul/CatalogRule/src/Http/Controllers/CatalogRuleController.php
>       *
Same here.

2022-07-20 08:13 UTC, devansh-webkul commented on packages/Webkul/CatalogRule/src/Http/Controllers/CatalogRuleController.php
>       * @param  int  $id
Same here.

2022-07-20 08:38 UTC, papnoisanjeev commented on packages/Webkul/CatalogRule/src/Http/Controllers/CatalogRuleController.php
>       * @param  int  $id
Done.

2022-07-20 09:30 UTC, devansh-webkul approved these changes

2022-07-23 07:09 UTC, Sanjaybhattwebkul commented
@papnoisanjeev 
The page should be auto focus on error

2022-07-23 07:47 UTC, papnoisanjeev commented
@Sanjaybhattwebkul 

As validation is from backend so most probably auto focus will not work here.

2022-07-23 11:25 UTC, Sanjaybhattwebkul approved these changes

2022-07-23 11:26 UTC, merged