Fixed issue #6418
bagisto/bagisto pull request #6582
Opened 2022-07-20 11:03 UTC by akathuria289

## Issue Reference
#6418

2022-07-20 14:06 UTC, jitendra-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/products/view/reviews.blade.php
>          )
Add if like below

if (
            (
                core()->getConfigData('catalog.products.review.guest_review')
                || auth()->guard('customer')->check()) && $orderCount != 0
                    
            ) 
            && $orderCount != 0
        )

2022-07-21 04:44 UTC, akathuria289 commented on packages/Webkul/Velocity/src/Resources/views/shop/products/view/reviews.blade.php
>          )
Fixed @jitendra-webkul

2022-07-21 10:26 UTC, jitendra-webkul commented on packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
> +                ->leftJoin('orders', 'order_items.order_id', 'orders.id')
Use tab here like below

`$orderedList = $this->orderItem->getModel()->where('product_id', $product->id)
                ->leftJoin('orders', 'order_items.order_id', 'orders.id')`

2022-07-21 10:28 UTC, jitendra-webkul commented on packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
> +                ->leftJoin('orders', 'order_items.order_id', 'orders.id')
Add tab here and for the below 2 statements too

2022-07-21 10:30 UTC, jitendra-webkul commented on packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
> +                ->get();
We can use the count function here instead of get function for getting all the items and then count

2022-07-21 10:31 UTC, jitendra-webkul commented on packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
> +                ->get();
And also pass id column to the count function

`->count('id')`

2022-07-21 10:33 UTC, jitendra-webkul commented on packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
> +                $orderedList = $this->orderItem->getModel()->where('product_id', $product->id)
->where('product_id', $product->id) should be in newline

2022-07-21 11:25 UTC, Sanjaybhattwebkul commented
@akathuria289 
Any update?

2022-07-21 12:24 UTC, akathuria289 commented
@Sanjaybhattwebkul Will fix and update soon

2022-07-22 05:39 UTC, akathuria289 commented
All above are fixed @jitendra-webkul Sir and @Sanjaybhattwebkul

2022-07-22 10:49 UTC, Sanjaybhattwebkul commented
@akathuria289 
**Not working**. please find the screenshot [Here](https://prnt.sc/KEFK97Y1D0OG)

2022-07-22 11:21 UTC, akathuria289 commented
@Sanjaybhattwebkul  Please check again it`s working

2022-07-23 05:44 UTC, Sanjaybhattwebkul commented
@akathuria289 
I create a new user and tried to review a random product and the review is submitted successfully. Please find the screenshot [Here](https://prnt.sc/CS7yaBQekf1c).
please check with a new user.

2022-07-23 05:50 UTC, devansh-webkul requested changes

2022-07-23 05:50 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Http/Controllers/ProductsCategoriesProxyController.php
> +                $orderCount = $this->orderItem->getModel()
Move this query to the model or repository and also use customer order relation to count data.

2022-07-23 07:06 UTC, devansh-webkul requested changes

2022-07-23 07:06 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view/reviews.blade.php
>              @if (
Same duplicate code used four times, make one helper, and reuse at all places.

2022-07-26 07:34 UTC, akathuria289 commented
@devansh-webkul  All above issues are fixed

2022-08-08 08:02 UTC, Sanjaybhattwebkul commented
@akathuria289 
**Not working,** there is an **exception** if the gust user is trying to **view all reviews** of any product, please find the screenshot [Here](https://prnt.sc/_jysefYMuG-d)

2022-08-09 10:12 UTC, Sanjaybhattwebkul commented
@akathuria289 
Any update?

2022-08-10 12:47 UTC, akathuria289 commented
@Sanjaybhattwebkul Please check issue is resolved

2022-08-19 13:25 UTC, Sanjaybhattwebkul commented
@akathuria289 
**Not fixed,** The customer is not able to **review** the product **after shipment,**

2022-08-23 09:51 UTC, Sanjaybhattwebkul commented
@jitendra-webkul 
As we discuss, the issue is invalid for which @abdulhamid-alattar  create this PR. So I am closing this PR.

2022-08-23 09:51 UTC, closed without merging