Fixed issue #5392
bagisto/bagisto pull request #6585
Opened 2022-07-20 12:39 UTC by akathuria289

## Issue Reference
 #5392

2022-07-20 12:46 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/filters/column-filter.vue
> +                        alert("Please enter the value");
Use translated value.

2022-07-20 12:48 UTC, devansh-webkul requested changes

2022-07-20 12:48 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/filters/column-filter.vue
> +                alert("Please select the filter");
Use translated value.

2022-07-20 13:17 UTC, akathuria289 commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/filters/column-filter.vue
> +                alert("Please select the filter");
Done

2022-07-20 13:17 UTC, akathuria289 commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/filters/column-filter.vue
> +                        alert("Please enter the value");
Done

2022-07-21 06:18 UTC, jitendra-webkul approved these changes

2022-07-21 06:19 UTC, merged

2022-07-21 06:47 UTC, Sanjaybhattwebkul commented
@akathuria289 
**Not working,** please run **_npm run prod_**  and do a fresh PR

2022-07-21 06:52 UTC, akathuria289 commented
@Sanjaybhattwebkul Created PR - https://github.com/bagisto/bagisto/pull/6587