Fixed issue #6417
bagisto/bagisto pull request #6589
Opened 2022-07-22 10:47 UTC by akathuria289

## Issue Reference
#6417

## Description
If the coupon is already applied then alert message will generate

2022-07-22 11:36 UTC, Sanjaybhattwebkul commented
@akathuria289 
The warning message should only be visible if the customer is applying the same coupon multiple times.
Please find the screenshot [Here](https://prnt.sc/S6kG7jqTD19p)

2022-07-23 05:33 UTC, devansh-webkul requested changes

2022-07-23 05:33 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Http/Controllers/CartController.php
> +        $couponStatus = request()->get('coupon_status');
What if the user adds correct coupon?

2022-07-23 05:33 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/views/checkout/cart/coupon.blade.php
> +                    already_applied: false,
Once applied is true, then for the correct one also this will show warning.

2022-07-23 12:46 UTC, Sanjaybhattwebkul commented
@akathuria289 
Any update ?

2022-07-25 05:02 UTC, closed without merging