Fixed issue #5463
bagisto/bagisto pull request #6612
Opened 2022-07-29 10:11 UTC by akathuria289

## Issue Reference
#5463

## How To Test This?
Add a filter to the product or category page and then click on clear all

2022-07-30 11:48 UTC, devansh-webkul requested changes

2022-07-30 11:48 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-filter-tags.vue
> +            location.reload();
Page should not be refresh.

2022-08-02 06:25 UTC, devansh-webkul requested changes

2022-08-02 06:25 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-filter-tags.vue
> +        <p @click="removeAllFilters" v-if="filters.length > 0">Clear All</p>
This should be inside the template and Clear should be translatable.

2022-08-02 06:25 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/datagrid-plus.vue
> +        clearAllFilters() {
Place this method after `removeFilter`.

2022-08-02 06:51 UTC, akathuria289 commented
Fixed

2022-08-02 07:09 UTC, Sanjaybhattwebkul commented
@akathuria289 
there is **no need** for the **clear all**  option If there is **only one applied filer**, please find the screenshot [Hee(https://prnt.sc/1-S2CPrRcT1S)
And the color of the **clear all** text should be **blue.**

2022-08-02 09:21 UTC, Sanjaybhattwebkul approved these changes

2022-08-03 05:31 UTC, merged