Fixed issue #6331
bagisto/bagisto pull request #6614
Opened 2022-07-30 10:40 UTC by akathuria289

## Issue Reference
#6331

2022-08-01 04:04 UTC, devansh-webkul requested changes

2022-08-01 04:04 UTC, devansh-webkul commented on packages/Webkul/BookingProduct/src/Resources/assets/sass/velocity.scss
> +            .icon {
Should be placed outside the `.icon` class and wrapped around `.booking-information` class.

2022-08-01 04:04 UTC, devansh-webkul commented on packages/Webkul/BookingProduct/src/Resources/assets/sass/default.scss
> +            }
Add proper spacing before curly braces.

2022-08-01 04:04 UTC, devansh-webkul commented on packages/Webkul/BookingProduct/src/Resources/assets/sass/velocity.scss
> +            }
Add proper spacing before curly braces.

2022-08-01 12:11 UTC, devansh-webkul approved these changes

2022-08-02 05:15 UTC, jitendra-webkul approved these changes

2022-08-02 05:15 UTC, merged