FIxed issue #5584
bagisto/bagisto pull request #6617
Opened 2022-07-30 11:59 UTC by akathuria289

## Issue Reference
#5584

2022-08-01 03:52 UTC, devansh-webkul requested changes

2022-08-01 03:52 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/assets/js/components/navigation/notification.vue
>              let this_this = this;
Make this variable,

~~~js
let self = this;
~~~

If don't want to use `self` then use the `arrow` function.

2022-08-01 03:52 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/assets/js/components/navigation/notification.vue
> +            let notifications = document.querySelector(".dropdown-list");
Use `ref`.

2022-08-01 06:49 UTC, devansh-webkul approved these changes

2022-08-02 05:18 UTC, jitendra-webkul approved these changes

2022-08-02 05:18 UTC, merged