Showing profile image when customer login.
bagisto/bagisto pull request #6618
Opened 2022-07-30 12:59 UTC by papnoisanjeev

## Issue Reference
#5464

## Description
Showing customer profile picture if customer login and have uploaded a profile picture.
Fixed for default and velocity theme.

https://prnt.sc/oVwv235YWgj8

2022-08-01 03:48 UTC, devansh-webkul requested changes

2022-08-01 03:48 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
> +                            <i style="vertical-align: top;"><img style="width:20px;margin-right:5px;height:20px;border-radius:50%;" src="{{ auth('customer')->user()->image_url }}" alt="{{ auth('custo
Use SCSS for styling.

2022-08-01 03:48 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/login-section.blade.php
> +            <i class="align-vertical-top"><img style="width:20px;margin-right:5px;height:20px;border-radius:50%;" src="{{ auth('customer')->user()->image_url }}" alt="{{ auth('customer')->user()->fir
Same here.

2022-08-01 04:53 UTC, papnoisanjeev commented on packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/login-section.blade.php
> +            <i class="align-vertical-top"><img style="width:20px;margin-right:5px;height:20px;border-radius:50%;" src="{{ auth('customer')->user()->image_url }}" alt="{{ auth('customer')->user()->fir
done.

2022-08-01 04:53 UTC, papnoisanjeev commented on packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
> +                            <i style="vertical-align: top;"><img style="width:20px;margin-right:5px;height:20px;border-radius:50%;" src="{{ auth('customer')->user()->image_url }}" alt="{{ auth('custo
done

2022-08-01 06:53 UTC, devansh-webkul requested changes

2022-08-01 06:53 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/login-section.blade.php
> +        @if( auth()->guard('customer')->user() && auth()->guard('customer')->user()->image)
Remove space after the bracket.

2022-08-01 06:53 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/layouts/top-nav/login-section.blade.php
> +        @endif
Add one line here.

2022-08-01 06:53 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/views/layouts/header/index.blade.php
> +                        @if( auth()->guard('customer')->user() && auth()->guard('customer')->user()->image)
Remove space after the bracket.

2022-08-01 07:07 UTC, devansh-webkul submitted a review, later dismissed

2022-08-02 05:17 UTC, jitendra-webkul commented
Resolve conflicts

2022-08-02 05:40 UTC, Sanjaybhattwebkul commented
@papnoisanjeev 
**not working** properly, the customer name is **not visible,** Please find the screenshot [Here](https://prnt.sc/bxRYI0Ux8nLc)
And please **resolve the conflicts.**

2022-08-02 05:50 UTC, Sanjaybhattwebkul commented
@papnoisanjeev 
This is **working fine** **only with** the **default** theme. but **getting** **issues** with the **velocity** theme

2022-08-02 06:31 UTC, Sanjaybhattwebkul commented
@papnoisanjeev 
The conflicts are **still not resolved.**

2022-08-02 07:14 UTC, papnoisanjeev commented
@Sanjaybhattwebkul 
Conflicts has been resolved here.

2022-08-02 07:39 UTC, Sanjaybhattwebkul commented
@papnoisanjeev 
The image option will only be for the velocity theme. the uploaded image should not be visible on the default theme.

2022-08-02 07:40 UTC, Sanjaybhattwebkul commented
And if the customer is updating the profile from the default theme, then the customer's image should not be removed.

2022-08-02 07:52 UTC, papnoisanjeev commented
@Sanjaybhattwebkul 

Removed profile pic for **default** theme as discussed as only need for velocity theme.

2022-08-02 08:31 UTC, Sanjaybhattwebkul commented
@papnoisanjeev 
The profile picture should not be updated if the customer is updating his profile from the default theme.

2022-08-02 10:14 UTC, Sanjaybhattwebkul commented
> @papnoisanjeev The profile picture should not be updated if the customer is updating his profile from the default theme.

any update?

2022-08-02 10:26 UTC, papnoisanjeev commented
@Sanjaybhattwebkul 

Fixed the issue (user profile remove) if anyone update profile using default theme.

2022-08-02 10:32 UTC, Sanjaybhattwebkul approved these changes

2022-08-02 11:13 UTC, Sanjaybhattwebkul commented
@papnoisanjeev 
**Still not working** the customer is **not able to delete** the profile picture,

2022-08-02 11:52 UTC, papnoisanjeev commented
@Sanjaybhattwebkul

Fixed.

2022-08-02 13:17 UTC, Sanjaybhattwebkul approved these changes

2022-08-02 13:22 UTC, merged