add formatDate for convert date
bagisto/bagisto pull request #6878
Opened 2022-10-11 19:13 UTC by KarimQaderi

## Issue Reference
https://github.com/bagisto/bagisto/issues/6867

## Description
I need to be able to convert date to Persian date

2022-10-12 06:55 UTC, devansh-webkul requested changes

2022-10-12 06:55 UTC, devansh-webkul commented on packages/Webkul/Core/src/Core.php
> +        if (is_string($date)){
Add space after the bracket.

2022-10-12 06:55 UTC, devansh-webkul commented on packages/Webkul/Ui/src/DataGrid/Traits/ProvideCollection.php
> +            } elseif ($column['type'] == 'datetime'){
Same here.

2022-10-12 06:55 UTC, devansh-webkul commented on packages/Webkul/Ui/src/DataGrid/Traits/ProvideCollection.php
> +            } elseif ($column['type'] == 'date'){
Same here.

2022-10-13 04:09 UTC, KarimQaderi commented
changes made as requested @devansh-webkul

2022-10-13 07:00 UTC, devansh-webkul approved these changes

2022-10-14 10:55 UTC, jitendra-webkul approved these changes

2022-10-14 10:55 UTC, merged