Fixed datagrid mass action issue
bagisto/bagisto pull request #7108
Opened 2022-11-17 12:52 UTC by prabhatkumaroc082

**Describe the issue**
Datagrid mass update feature is not working due to object used [here](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-table.vue#L57)

**Expected result**
datagrid mass update must function

2022-11-18 05:32 UTC, devansh-webkul commented
Need to check these cases also,
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Category/src/Http/Controllers/CategoryController.php#L217

2022-11-18 07:29 UTC, Sanjaybhattwebkul commented
@prabhatkumaroc082 
The **mass** action is **working** in the admin panel, can you please **elaborate**?

2022-11-18 08:02 UTC, prabhatkumaroc082 commented
> Need to check these cases also, https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Category/src/Http/Controllers/CategoryController.php#L217

@devansh-webkul applied changes.

2022-11-18 08:05 UTC, devansh-webkul requested changes

2022-11-18 08:05 UTC, devansh-webkul commented on packages/Webkul/Category/src/Http/Controllers/CategoryController.php
> +            !isset($data['mass-action-type'])
Add space after `!`.

2022-11-18 08:05 UTC, devansh-webkul commented on packages/Webkul/Product/src/Http/Controllers/ProductController.php
> +            !isset($data['mass-action-type'])
Same here.

2022-11-18 08:05 UTC, devansh-webkul commented on packages/Webkul/Product/src/Http/Controllers/ReviewController.php
> +                        !isset($data['mass-action-type'])
Same here.

2022-11-18 08:26 UTC, devansh-webkul commented
@Sanjaybhattwebkul,

Please test this.

2022-11-18 09:07 UTC, prabhatkumaroc082 commented
> @prabhatkumaroc082 The **mass** action is **working** in the admin panel, can you please **elaborate**?

@Sanjaybhattwebkul 

you will find object [here](https://user-images.githubusercontent.com/50438561/202662517-af8f4ad5-1d05-4cfb-8161-f335318bee57.png) in dropdown values.

you might not be facing the issue due to validation added [here](https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Category/src/Http/Controllers/CategoryController.php#L217) if you closely look into condition `! $data['mass-action-type'] == 'update'` it will always return false even if key 'mass-action-type' doesn't contain value 'update'

i applied some improvements so that these conditions should work only when mass type is 'update'. For now, this validation is not in use.

2022-11-22 06:37 UTC, Sanjaybhattwebkul commented
@prabhatkumaroc082 
Please resolve the conflicts.

2022-11-22 07:02 UTC, prabhatkumaroc082 commented
@Sanjaybhattwebkul review now.

2022-11-22 07:13 UTC, Sanjaybhattwebkul commented
@devansh-webkul 
The **mass** actions are **working fine** in admin panel ,please find the screenshot [Here](https://prnt.sc/ojlXCNslnKCW)

2022-11-22 07:20 UTC, devansh-webkul approved these changes

2022-11-22 07:25 UTC, merged