Issue Fixed #7080
bagisto/bagisto pull request #7147
Opened 2022-11-26 10:39 UTC by akhtarkhan1

## Issue Reference
Issue Fixed #7080

2022-11-26 10:52 UTC, Sanjaybhattwebkul commented
@akhtarkhan1 
This is **working fine**, please find the **screenshot** [Here](https://prnt.sc/24osCbuAY3-m)

2022-11-26 10:52 UTC, Sanjaybhattwebkul submitted a review, later dismissed

2022-11-26 11:10 UTC, devansh-webkul requested changes

2022-11-26 11:10 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/bundle-items.blade.php
> +                    <tbody style="border-bottom: 1px solid #e8e8e8;">
Use class don't add direct styling.

2022-11-26 11:10 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/bundle-items.blade.php
> +                                <p style="text-align:center;">{{ __('admin::app.catalog.products.no-product-added') }} </p>
Same here.

2022-11-26 11:10 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/bundle-items.blade.php
> +            <button type="button" class="btn btn-md btn-primary" @click="addOption" style="margin-bottom: 20px;">
Same here.

2022-11-28 11:26 UTC, jitendra-webkul commented
Resolve conflicts

2022-11-30 08:35 UTC, Sanjaybhattwebkul commented
@akhtarkhan1 
Now, this issue is **fixed**. Please find the **screenshot** [Here](https://prnt.sc/H7X6xQhL5EDg)

2022-11-30 08:36 UTC, Sanjaybhattwebkul approved these changes

2022-11-30 08:55 UTC, jitendra-webkul approved these changes

2022-11-30 08:56 UTC, merged