Issue #6972  Fixed
bagisto/bagisto pull request #7179
Opened 2022-12-06 06:42 UTC by Sanjaybhattwebkul

## Issue Reference
#6972

| Before  |  After |
|-----------|---------|
| ![before](https://user-images.githubusercontent.com/86394952/205839787-8f2cafa1-161c-44a0-9f27-e493d471dca1.png) | ![after](https://user-images.githubusercontent.com/86394952/205839820-2462cbe5-f8f1-4aad-b046-659bb8ddb314.png)

2023-02-13 05:34 UTC, devansh-webkul requested changes

2023-02-13 05:34 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/layouts/particals/header-compts.blade.php
> +            @include('shop::checkout.cart.mini-cart')
Add a new line above include.

2023-02-13 05:34 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/products/wishlist.blade.php
> +        <a
Add new line.

2023-02-13 05:34 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/layouts/header/index.blade.php
Remove this line also.

2023-02-21 05:54 UTC, devansh-webkul approved these changes

2023-02-21 05:55 UTC, jitendra-webkul approved these changes

2023-02-21 05:55 UTC, merged