Admin Profile Issue Resolved
bagisto/bagisto pull request #7193
Opened 2022-12-13 06:41 UTC by Sanjaybhattwebkul

>Admin Profile Issue Resolved

| Before  |  After |
|-----------|---------|
| ![before](https://user-images.githubusercontent.com/86394952/207244738-a63984f1-563c-40fc-bdae-a1c7037a9053.png) | ![after](https://user-images.githubusercontent.com/86394952/207244768-aca3c9a6-3118-44f2-ac63-6d92d9a7e0dd.png)|

2023-02-13 05:37 UTC, devansh-webkul requested changes

2023-02-13 05:37 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/layouts/nav-top.blade.php
> +                                <dark style="margin-top: -9px;width: 70px; height:0px"></dark>
Avoid using inline styles.

2023-02-13 05:37 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/layouts/nav-top.blade.php
> +                                <dark style="margin-top: -9px;width: 70px; height:0px"></dark>
Avoid using inline styles.

2023-02-21 10:37 UTC, devansh-webkul approved these changes

2023-02-23 07:02 UTC, jitendra-webkul approved these changes

2023-02-23 07:02 UTC, merged