Issue #7198 fixed
bagisto/bagisto pull request #7207
Opened 2022-12-27 06:05 UTC by suraj-webkul

#7198 
> Return latest product when updating the products variants.

2022-12-27 08:44 UTC, Sanjaybhattwebkul approved these changes

2022-12-27 09:16 UTC, Sanjaybhattwebkul requested changes

2022-12-27 09:16 UTC, Sanjaybhattwebkul commented on packages/Webkul/Product/src/Repositories/ProductRepository.php
> +        return $updated_product;
same here

2022-12-27 09:16 UTC, Sanjaybhattwebkul commented on packages/Webkul/Product/src/Repositories/ProductRepository.php
> +            $updated_product['channels'] = $data['channels'];
Use camel case like this: $updatedProduct

2022-12-27 09:53 UTC, Sanjaybhattwebkul approved these changes

2022-12-28 07:03 UTC, devansh-webkul requested changes

2022-12-28 07:03 UTC, devansh-webkul commented on packages/Webkul/Product/src/Repositories/ProductRepository.php
> +        $updatedProduct = $this->find($id);
I think $product->refresh() will do trick here. No need of again taking new variables.

2022-12-28 10:21 UTC, closed without merging