Enhancement #7208 done
bagisto/bagisto pull request #7209
Opened 2022-12-27 12:11 UTC by amitwebkul

#7208 
> Add arrow class for status filter.

2022-12-27 12:32 UTC, Sanjaybhattwebkul commented
Please **compile** the files, Please **run** the **below command** before pushing your code.

**_npm run prod_**

2022-12-28 07:00 UTC, devansh-webkul requested changes

2022-12-28 10:42 UTC, Sanjaybhattwebkul commented
@amitwebkul 
The icon should be **slightly bold.** please find the **screenshot** [Here](https://prnt.sc/Cj4nSFtByFx2)

2022-12-29 11:45 UTC, Sanjaybhattwebkul commented
@amitwebkul 
This is **working fine,** Please find the **screenshot** [Here](https://prnt.sc/eGtj-Q-f_vSC)

2023-02-13 05:49 UTC, devansh-webkul requested changes

2023-02-13 05:49 UTC, devansh-webkul commented on packages/Webkul/Ui/reflect
> + @ multi - the changes on ui main[4]
Why this file is pushed?

2023-02-13 05:49 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/filters/column-filter.vue
> +                        <span class="button-span">
Add new line.

2023-02-13 05:49 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/filters/column-filter.vue
> +                        <span>
Same here.

2023-02-13 05:49 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
> +.drop-down-arrow {
New line.

2023-02-13 05:49 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
> +@media only screen and (max-width: 1440px) {
New line.

2023-02-13 11:19 UTC, jitendra-webkul commented
Resolve conflicts

2023-02-21 06:29 UTC, Sanjaybhattwebkul commented
@amit-webkul 
Resolve the **conflicts**.

2023-03-16 06:59 UTC, Sanjaybhattwebkul commented
@amit-webkul 
Resolve the **conflicts**

2023-03-16 09:37 UTC, Sanjaybhattwebkul commented
@amit-webkul 
Getting **duplicate commits.** please **resolved**

2023-03-16 09:42 UTC, Sanjaybhattwebkul commented
**1.** Git fetch --all
**2.** git reset --hard 38f7cd3
**3.** git push -u origin filter-ui-issue -f

2023-03-16 09:43 UTC, closed without merging