Issue Fixed | Tax category for variants #7201
bagisto/bagisto pull request #7211
Opened 2022-12-28 10:06 UTC by suraj-webkul

## Issue Reference
#7201

2022-12-28 10:34 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
If the admin is **removing** the **tax** from the **parent product,** then the **tax** should be **removed** from all **child products**

2022-12-28 13:31 UTC, devansh-webkul requested changes

2022-12-28 13:31 UTC, devansh-webkul commented on packages/Webkul/Product/src/Repositories/ProductRepository.php
> +
Move this code to product's individual instance type,
https://github.com/bagisto/bagisto/blob/master/packages/Webkul/Product/src/Type/Configurable.php#L183

2022-12-29 05:27 UTC, Sanjaybhattwebkul commented
new pr created for the same issue: https://github.com/bagisto/bagisto/pull/7213

2022-12-29 05:27 UTC, closed without merging