Issue #7230 fixed
bagisto/bagisto pull request #7232
Opened 2023-01-13 10:47 UTC by Sanjaybhattwebkul

#7230
> Add span tag inside tbody/th

2023-02-13 05:57 UTC, devansh-webkul requested changes

2023-02-13 05:57 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-table.vue
> +
Remove the new line.

2023-02-13 05:57 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/sass/app.scss
> +            span{
Add one space after the span.

2023-02-23 08:25 UTC, devansh-webkul requested changes

2023-02-23 08:25 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-table.vue
> +                        class="grid_head"
Class name should be `kebab-case`.

2023-03-22 06:46 UTC, amitkumarqa commented
@Sanjaybhattwebkul,

Resolve the conflict.

2023-03-28 12:35 UTC, closed without merging