Enhancement #7202 done
bagisto/bagisto pull request #7234
Opened 2023-01-16 11:20 UTC by Rachana1005

## Issue Reference
#7202
>Option added for upload category banner

2023-01-16 12:50 UTC, Sanjaybhattwebkul commented
@Rachana1005 
**Not working,** please find the screenshot [Here](https://prnt.sc/8_orbmh7WAgo)

2023-01-16 13:09 UTC, Rachana1005 commented
@Sanjaybhattwebkul 
Please check the changes. It's done from my side

2023-01-16 13:15 UTC, Sanjaybhattwebkul commented
@Rachana1005 
Now this is **working fine**, please find the screenshot [Here](https://prnt.sc/VwCAwJmmKcm4)

2023-01-16 13:15 UTC, Sanjaybhattwebkul approved these changes

2023-01-16 13:31 UTC, Sanjaybhattwebkul commented
@Rachana1005 
**Improve the UI** of the category banner in the **admin panel**, please take a reference from [Here](https://prnt.sc/prCqderpyxJx)

2023-01-16 13:47 UTC, vivek-webkul requested changes

2023-01-16 13:47 UTC, vivek-webkul commented on packages/Webkul/Admin/src/Resources/views/catalog/categories/create.blade.php
> +                                <span class="control-info mt-10">{{ __('admin::app.catalog.categories.image-size') }}</span>
@Rachana1005 
Need to mention the correct suggestion size for the banner image. Here you used the suggestion of the Image size.

2023-01-16 13:47 UTC, vivek-webkul commented on packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
> +                                <span class="control-info mt-10">{{ __('admin::app.catalog.categories.image-size') }}</span>
@Rachana1005 
Need to mention the correct suggestion size for the banner image. Here you used the suggestion of the Image size.

2023-01-16 13:47 UTC, vivek-webkul commented on packages/Webkul/Category/src/Database/Migrations/2023_01_16_163456_add_category_banner_to_categories_table.php
> +            $table->text('category_banner')->nullable();
@Rachana1005 
Add column exists check.

2023-01-16 13:47 UTC, vivek-webkul commented on packages/Webkul/Category/src/Repositories/CategoryRepository.php
> +        $this->uploadBanner($data,$category);
@Rachana1005 

Why, we are using new method, we can use the $type param for the banner image.

2023-01-17 09:46 UTC, Sanjaybhattwebkul commented
@Rachana1005 
The UI part is still not fixed.

2023-01-18 05:27 UTC, Sanjaybhattwebkul commented
@Rachana1005 
**Still not fixed** for the admin panel. Please find the **screenshot** [Here](https://prnt.sc/EMJbWbvWGdOg)

2023-01-18 05:34 UTC, Rachana1005 commented
@Sanjaybhattwebkul 
It's working from my side
![Screenshot from 2023-01-18 11-03-57](https://user-images.githubusercontent.com/120095673/213092391-8a2f3cf8-32a6-41d9-a00a-54b0ab74ece2.png)

2023-01-18 08:06 UTC, vivek-webkul requested changes

2023-01-18 08:06 UTC, vivek-webkul commented on packages/Webkul/Admin/src/Resources/views/catalog/categories/edit.blade.php
> +                                <span class="control-error" v-if="{!! $errors->has('image.*') !!}">
Wrong error field check for category_banner.

2023-01-18 08:06 UTC, vivek-webkul commented on packages/Webkul/Category/src/Repositories/CategoryRepository.php
> +         $this->uploadImages($data, $category, 'category_banner');
No validation(mime type) form post for category_banner image type.

2023-01-19 04:53 UTC, Sanjaybhattwebkul commented
@Rachana1005 
Now, this i**s working fine,** please find the  screenshot [Here](https://prnt.sc/ZtpPsL_dP7Kz)

2023-01-19 04:56 UTC, Sanjaybhattwebkul approved these changes

2023-02-13 06:01 UTC, devansh-webkul requested changes
This pull request is having 155 file changes. Please check.

2023-02-13 07:47 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
Any update?

2023-02-17 09:40 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
Closing this pull request, because another pull request is created for the same issue.

2023-02-17 09:40 UTC, closed without merging