Issue #7200 fixed
bagisto/bagisto pull request #7249
Opened 2023-01-30 13:28 UTC by vijay-webkul

## Issue Reference
#7200

2023-01-31 06:28 UTC, Sanjaybhattwebkul commented
@vijay-webkul 
**Not working**, **still** getting the **same** issue, please find the screenshot [Here](https://prnt.sc/ifTck57tCKPV)

2023-01-31 07:48 UTC, vijay-webkul commented
I have checked not an issue, it is working properly See the screenshot [here](url)
![Tax-Screenshot](https://user-images.githubusercontent.com/123063852/215697945-eec23fc0-7417-4dcf-bf20-12fc52070dc9.png)

2023-01-31 08:17 UTC, Sanjaybhattwebkul requested changes

2023-01-31 08:17 UTC, Sanjaybhattwebkul commented on packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
> +                                    if(address.city){
add space after if and before {

2023-01-31 08:17 UTC, Sanjaybhattwebkul commented on packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
> +                                        this.address.billing.state = address.state;
same here

2023-01-31 08:17 UTC, Sanjaybhattwebkul commented on packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
> +                                    if(address.country){
same here

2023-02-13 08:03 UTC, vijay-webkul commented
all changes has done.

2023-02-21 06:21 UTC, Sanjaybhattwebkul commented
@vijay-webkul 
**Not working**, the **checkout page** is getting **blank**.

2023-02-23 06:41 UTC, Sanjaybhattwebkul commented
@vijay-webkul 
Any update?

2023-02-23 07:07 UTC, Sanjaybhattwebkul approved these changes

2023-02-23 07:09 UTC, closed without merging