issue #7216
bagisto/bagisto pull request #7257
Opened 2023-02-01 14:29 UTC by rachana-webkul

## Issue Reference
Issue Id 7079

## Description
Now on adding configurable product the minimum quantity of the configurable product is showing on the user side

2023-02-02 05:49 UTC, Sanjaybhattwebkul commented
@jitendra-webkul 
As we discuss. i am putting this PR on hold

2023-02-03 06:17 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
**Not working**, please find the screenshot [Here](https://prnt.sc/z66B93JS6i09)

2023-02-06 13:59 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
Any update?

2023-02-06 14:23 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
The space should be according to the card content on the home page.

2023-02-13 11:31 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
Please resolve the **conflicts**

2023-02-13 12:02 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
**Not working**, The configurable product's **price** should be visible like: **$10.00**  _As low as_

2023-02-13 13:28 UTC, rachana-webkul commented
@Sanjaybhattwebkul  now price-lable add

2023-02-16 08:14 UTC, rachana-webkul commented
@Sanjaybhattwebkul 
Conflicts **resolved**, please verify

2023-02-16 09:27 UTC, devansh-webkul requested changes

2023-02-16 09:27 UTC, devansh-webkul commented on packages/Webkul/Product/src/Type/Configurable.php
> +     * Return variants of configurable product.
Add return type in heredoc.

2023-02-16 09:27 UTC, devansh-webkul commented on packages/Webkul/Product/src/Type/Configurable.php
> +        $product =  $this->product;
No need of variable directly pass the value.

2023-02-16 09:27 UTC, devansh-webkul commented on packages/Webkul/Product/src/Type/Configurable.php
> +        $product =  $this->product;
Same here.

2023-02-16 09:45 UTC, rachana-webkul commented
@devansh-webkul 
resolved issue, please verify.

2023-02-16 10:47 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
**Not working**, please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63ee098693ea2803a944bfae)

2023-02-16 11:08 UTC, rachana-webkul commented
@Sanjaybhattwebkul 
product label added, please verify

2023-02-16 11:27 UTC, devansh-webkul requested changes

2023-02-16 11:27 UTC, devansh-webkul commented on packages/Webkul/Product/src/Type/Configurable.php
> +
Remove one line from here.

2023-02-16 11:40 UTC, rachana-webkul commented
@devansh-webkul 
spaces resolved ,please verify

2023-02-17 11:20 UTC, rachana-webkul commented
@Sanjaybhattwebkul 
configuration price fixed,please verify

2023-02-17 11:32 UTC, devansh-webkul requested changes

2023-02-17 11:32 UTC, devansh-webkul commented on packages/Webkul/Product/src/Type/Configurable.php
> +     * @return array
Add a new line and change the return type to float.

2023-02-17 11:32 UTC, devansh-webkul commented on packages/Webkul/Product/src/Type/Configurable.php
> +            $prices[$variant->id] = $variant->getTypeInstance()->getProductPrices();
No need to add $prices[$variant->id] as your end result is just taking minimum from the array.

Just pass it like this,

~~~php
$prices[] = $variant->getTypeInstance()->getProductPrices();
~~~

2023-02-17 11:38 UTC, rachana-webkul commented
@devansh-webkul 
changes done,please verify

2023-02-20 06:54 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
**Not fixed,** the product is wrong on the home page,

2023-02-21 08:18 UTC, rachana-webkul commented
@Sanjaybhattwebkul 
conflict resolved, please verify

2023-02-22 04:56 UTC, rachana-webkul commented
@Sanjaybhattwebkul 
configurable variant price changed,please verify

2023-02-23 06:45 UTC, rachana-webkul commented
@Sanjaybhattwebkul 
product price fixed for configurable products,please verify

2023-02-23 07:31 UTC, rachana-webkul commented
@Sanjaybhattwebkul 
lowest variant price of configurable product is visible, please verify

2023-04-03 06:33 UTC, rachana-webkul commented
@Sanjaybhattwebkul  conflicts resolved,please verify

2023-04-03 07:51 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
**Still** getting the **same issue**. please find the screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/642a8535f0168c07d9e98ecd)

2023-04-04 08:27 UTC, rachana-webkul commented
@Sanjaybhattwebkul  it's working please verify

2023-04-06 13:47 UTC, Sanjaybhattwebkul approved these changes

2023-04-06 13:48 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
This is **working fine.**

2023-04-10 05:15 UTC, Amitk-webkul commented
@rachana-webkul 
with the tax on the Product page tax message layout is not set.[Here](https://prnt.sc/1TNG8JStrPcl)

2023-04-10 09:39 UTC, devansh-webkul commented
> @rachana-webkul with the tax on the Product page tax message layout is not set.[Here](https://prnt.sc/1TNG8JStrPcl) After deleting a variant product. It is not adding products to the cart. [Here](https://tinyurl.com/292ucjll)

Is this reproducible in master, if so then we will fix in the new issue as this pull request scope is to get the min price from all variants.

2023-04-10 09:52 UTC, Amitk-webkul commented
@devansh-webkul 
The above issues are not replicated in the master.

2023-04-10 13:32 UTC, closed without merging