issue #7158
bagisto/bagisto pull request #7261
Opened 2023-02-03 11:42 UTC by rachana-webkul

## Issue Reference
#7158

2023-02-06 14:24 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
The space should be according to the card content on the home page.

2023-02-16 09:24 UTC, devansh-webkul requested changes

2023-02-16 09:24 UTC, devansh-webkul commented on packages/Webkul/Product/src/Type/Bundle.php
> +                $priceHtml .= '<span class="bundle-regular-price" style="margin-left: 6px;">' . $prices['to']['regular_price']['formatted_price'] . '</span>'
Use classes instead of inline style.

2023-02-16 09:24 UTC, devansh-webkul commented on packages/Webkul/Product/src/Type/Bundle.php
> +
Remove one line from here.

2023-02-16 09:24 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/products/price.blade.php
> +<div class="product-price" style="height: 2.5rem;">
Use classes.

2023-02-16 10:53 UTC, rachana-webkul commented
@devansh-webkul 
classes added and spaces resolved, please verify

2023-02-16 11:30 UTC, devansh-webkul reviewed
@Sanjaybhattwebkul,

Retest this again as classes added in styling.

2023-02-20 06:56 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
Please resolve the **conflicts**.

2023-02-20 07:49 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
**Not fixed** for **mobile** view, Please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63f32576bf991905516bade8)

2023-02-21 06:12 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
Resolve the **conflicts**.

2023-02-21 06:26 UTC, rachana-webkul commented
@Sanjaybhattwebkul 
conflict resolved,please verify

2023-02-22 09:38 UTC, rachana-webkul commented
@Sanjaybhattwebkul 
ui changes done, please verify

2023-02-22 09:40 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
Getting **duplicate commits.** please resolve

2023-02-22 12:46 UTC, rachana-webkul commented
@Sanjaybhattwebkul 
Ui fixed ,please verify

2023-02-23 05:50 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
The **_add to car_**t button is not responsive for mobile.

2023-02-23 07:19 UTC, rachana-webkul commented
@Sanjaybhattwebkul 
Button is now responsive according to the mobile view, please verify

2023-02-23 07:24 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
The product price is overriding the add to cart button in mobile view, please find the screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/63f714a7aac9534fac26b8b5)

2023-02-24 05:04 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
Now, this is **working fine**, please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63f8452caac9534fac26eaf0)

2023-02-24 05:04 UTC, Sanjaybhattwebkul approved these changes

2023-03-03 10:09 UTC, devansh-webkul approved these changes

2023-03-06 05:10 UTC, jitendra-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/app.scss
> +        margin-top: -20px;
Add new line after this statement

2023-03-06 05:10 UTC, jitendra-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +        .product-image-container img {
Fixed indentation

2023-03-06 05:11 UTC, jitendra-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +            .product-image-container img {
Fixed indentation

2023-03-06 05:11 UTC, jitendra-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +
Remove line from here

2023-03-06 05:11 UTC, jitendra-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +                            }
Fixed indentation

2023-03-06 05:11 UTC, jitendra-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
>          .product-image-container img {
Fixed indentation

2023-03-06 05:12 UTC, jitendra-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +
Remove new line

2023-03-06 05:12 UTC, jitendra-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +
Remove new line

2023-03-14 09:55 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
Resolve the conflicts

2023-03-14 11:12 UTC, rachana-webkul commented
@Sanjaybhattwebkul @jitendra-webkul 
conflicts and comments resolved,please verify

2023-03-22 07:20 UTC, Amitk-webkul commented
@rachana-webkul 

Please resolved the conflicts.

2023-03-28 13:17 UTC, devansh-webkul approved these changes

2023-03-30 10:42 UTC, closed without merging