issue Fixed #7168
bagisto/bagisto pull request #7263
Opened 2023-02-06 06:29 UTC by vijay-webkul

## Issue Reference
#7168 FIXED ISSUE

2023-02-06 07:59 UTC, Sanjaybhattwebkul requested changes

2023-02-06 07:59 UTC, Sanjaybhattwebkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/datagrid-plus.vue
> +            this.$nextTick(()=>{
Add space after =>

2023-02-06 08:06 UTC, vijay-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/datagrid-plus.vue
> +            this.$nextTick(()=>{
ok, I have done.

2023-02-06 08:35 UTC, Sanjaybhattwebkul commented
@vijay-webkul 
**Not working.** Please **compile** the **vue file** before pushing the code. run the given **command** 

_**npm run i
npm run prod**_

2023-02-06 13:38 UTC, Sanjaybhattwebkul commented
@vijay-webkul 
**Not working**, please find the below screenshots.

![screenshot_1675690434762](https://user-images.githubusercontent.com/86394952/216985604-04c01ea5-2888-4632-90c3-07f29c856559.png)



![screenshot_1675690468439](https://user-images.githubusercontent.com/86394952/216985636-fb75d225-a3e0-4259-ada5-0fa21af9ad31.png)

2023-02-07 07:35 UTC, Sanjaybhattwebkul commented
Closing this pr. new pr is created for this issue. https://github.com/bagisto/bagisto/pull/7269

2023-02-07 07:35 UTC, closed without merging