Shippingmethod
bagisto/bagisto pull request #7300
Opened 2023-02-14 12:54 UTC by rachana-webkul

## Issue Reference
#3454

2023-02-15 05:15 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
This is **working fine**, please find the **screenshot** [Here](https://webkul.chatwhizz.com/share/screenshot/63ec6a56aac9534fac2538f5)

2023-02-15 05:17 UTC, Sanjaybhattwebkul approved these changes

2023-02-16 10:02 UTC, devansh-webkul requested changes

2023-02-16 10:02 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
> +                        var methodRateObject = this.methods[firstMethod]['rates'][0];
Use `let` instead of `var`.

2023-02-16 10:02 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
>                      for (var i in shippingHtml.staticRenderFns) {
let `i`.

2023-02-16 10:02 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
> +                                if (this.step_numbers[response.data.jump_to_section] == 2 ) {
Remove space after 2.

2023-02-17 11:28 UTC, Sanjaybhattwebkul commented
@rachana-webkul 
Any update?

2023-02-17 11:44 UTC, rachana-webkul commented
@Sanjaybhattwebkul @devansh-webkul 
changes done,please verify

2023-02-17 11:50 UTC, devansh-webkul approved these changes

2023-02-20 06:35 UTC, jitendra-webkul approved these changes

2023-02-20 06:36 UTC, merged