Fixing #7264 issue
bagisto/bagisto pull request #7303
Opened 2023-02-15 13:51 UTC by suraj-webkul

Fixing this isuse.

2023-02-16 06:54 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
**Not working**, Still, **duplicate addresses** are getting saved.Please find the **screenshot** [here](https://webkul.chatwhizz.com/share/screenshot/63edd31b93ea2803a944aa7d)

2023-02-16 14:30 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
This is **working fine**.

2023-02-16 14:30 UTC, Sanjaybhattwebkul submitted a review, later dismissed

2023-02-20 06:26 UTC, devansh-webkul commented
Conflicts not resolved properly take help from @Sanjaybhattwebkul.

2023-02-28 07:23 UTC, Sanjaybhattwebkul approved these changes

2023-02-28 07:25 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
This is working fine

2023-03-29 08:18 UTC, Sanjaybhattwebkul requested changes

2023-03-29 08:18 UTC, Sanjaybhattwebkul commented on packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
> +                            if (this.$refs.billingSaveAsAddress && this.$refs.billingSaveAsAddress.checked) {
Break conditions in 2 lines

2023-03-29 08:19 UTC, suraj-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/checkout/onepage.blade.php
> +                            if (this.$refs.billingSaveAsAddress && this.$refs.billingSaveAsAddress.checked) {
breaked into 2 lines

2023-04-03 10:33 UTC, Amitk-webkul commented
@suraj-webkul 
This is working fine.

2023-04-06 14:09 UTC, jitendra-webkul approved these changes

2023-04-06 14:09 UTC, merged