Issue #7172 fixed
bagisto/bagisto pull request #7305
Opened 2023-02-16 11:16 UTC by vijaysingh-webkul

## Issue Reference
#7172

2023-02-23 13:17 UTC, Sanjaybhattwebkul commented
@vijaysingh-webkul 
Resolve the **conflicts**.

2023-03-01 06:59 UTC, Sanjaybhattwebkul commented
@vijaysingh-webkul 
Still getting the **conflicts**.

2023-03-01 07:34 UTC, Sanjaybhattwebkul commented
@vijaysingh-webkul 
**Not working** as **expected resul**t. please take a **reference** from the [attached screenshot](https://github.com/bagisto/bagisto/issues/7172)

2023-03-02 15:21 UTC, devansh-webkul requested changes

2023-03-02 15:21 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/js/UI/components/product-collections.vue
> +        },
Add a new line before and after the end of the function.

2023-04-06 13:04 UTC, closed without merging