UI issue resolved
bagisto/bagisto pull request #7312
Opened 2023-02-17 12:14 UTC by gitesh-webkul

## Issue Reference
#7190

2023-02-20 08:28 UTC, Sanjaybhattwebkul commented
@gitesh-webkul 
Resolve the **conflicts**.

2023-02-21 05:04 UTC, Sanjaybhattwebkul commented
@gitesh-webkul 
resolve the **conflicts**

2023-02-21 05:59 UTC, devansh-webkul requested changes

2023-02-21 05:59 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/home/advertisements/advertisement-four.blade.php
> +                <div class="advertisement-container-block adv2">
Use a meaningful name like the first one is `advertisement-container-block` then the remaining classes should follow the convention like `advertisement-1` or may be try to handle without numbering like `advertisement-container-block advertisement-small advertisement-large advertisement-medium`  whatever is suitable.

2023-02-21 11:29 UTC, Sanjaybhattwebkul commented
@gitesh-webkul 
**Still not fixed**, the images are getting **stretched** in **mobile** view on **home page.**, Please find the screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/63f4ab0faac9534fac264f36)

2023-02-23 07:17 UTC, Sanjaybhattwebkul submitted a review, later dismissed

2023-03-20 12:24 UTC, devansh-webkul submitted a review, later dismissed

2023-03-20 13:47 UTC, Sanjaybhattwebkul approved these changes

2023-03-21 11:06 UTC, merged