Issue #7157 fixed.
bagisto/bagisto pull request #7318
Opened 2023-02-20 13:56 UTC by suraj-webkul

Issue #7157 fixed.
Add drag and drop option

2023-02-21 13:40 UTC, akathuria289 commented on packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/images.blade.php
> +
Remove this space @suraj-webkul

2023-02-22 07:04 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
Add the same for the category section too.

2023-02-22 11:50 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
**Not working** in for categories.

2023-02-22 11:56 UTC, suraj-webkul commented
Please publish assets then try again

2023-02-23 06:15 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
**Not working,** if trying to **drop** the **variants** image.

2023-02-24 03:55 UTC, suraj-webkul commented on packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/images.blade.php
> +
space removed

2023-02-24 09:51 UTC, akathuria289 approved these changes

2023-02-27 12:39 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
This is **working fine.**

2023-02-27 12:40 UTC, Sanjaybhattwebkul submitted a review, later dismissed

2023-03-01 14:10 UTC, akathuria289 submitted a review, later dismissed

2023-03-03 10:00 UTC, devansh-webkul requested changes

2023-03-03 10:00 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
>                  }
Optimize this. Pass it through AJAX request.

2023-03-22 08:07 UTC, Amitk-webkul commented
@suraj-webkul,

Resolve the conflicts.

2023-03-22 08:14 UTC, suraj-webkul commented
[Amitk-webkul](https://github.com/Amitk-webkul) Conflicts Resolved

2023-03-28 11:45 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
any update?

2023-03-28 11:54 UTC, closed without merging