Issue #6367 fixed
bagisto/bagisto pull request #7319
Opened 2023-02-21 06:03 UTC by suraj-webkul

Issue #6367
The percentage of the discount now visible on the product view page if there is any discount for the product.

2023-02-21 08:26 UTC, akathuria289 commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/home.scss
> +    font-size: 15px !important
@suraj-webkul remove important from font-size

2023-02-23 05:54 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
Need to **improve the UI**. please find the screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/63f6ff4793ea2803a945fb35)

2023-02-23 11:58 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
Any update?

2023-02-23 14:23 UTC, suraj-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/home.scss
> +    font-size: 15px !important
Removed

2023-02-24 10:53 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
Still getting the spacing issue. there should be a space of 4px between all prices.

2023-02-24 11:56 UTC, suraj-webkul commented
Please publish assests all changes are done

2023-02-27 06:50 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
**Not fix** for **bundle** product, please find the screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/63fc52a2aac9534fac273b8b)

2023-02-27 13:25 UTC, Sanjaybhattwebkul commented
@devansh-webkul 
Please review this pr.

2023-02-27 13:26 UTC, Sanjaybhattwebkul approved these changes

2023-03-01 14:09 UTC, akathuria289 approved these changes
@suraj-webkul resolve the conflict

2023-03-20 12:21 UTC, devansh-webkul requested changes

2023-03-21 08:26 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
resolve the duplicate commits.

2023-03-21 08:31 UTC, closed without merging

2023-03-29 10:08 UTC, akathuria289 submitted a review, later dismissed

2023-03-29 10:08 UTC, akathuria289 commented on packages/Webkul/Product/src/Type/Bundle.php
> +            } elseif ($value && $value) {
remove one $value

2023-04-03 10:25 UTC, Amitk-webkul commented
@suraj-webkul 
Not fixed for bundle product, please check the reference [Here](https://webkul.chatwhizz.com/share/screenshot/642aa98a2a666707c4096f04)

2023-04-05 07:19 UTC, suraj-webkul commented on packages/Webkul/Product/src/Type/Bundle.php
> +            } elseif ($value && $value) {
done

2023-04-05 07:22 UTC, suraj-webkul commented
> @suraj-webkul Not fixed for bundle product, please check the reference [Here](https://webkul.chatwhizz.com/share/screenshot/642aa98a2a666707c4096f04)

Please try to run 
~~~
npm run watch  
~~~

After testing please run
~~~
npm run dev
~~~

in Velocity package/module

2023-04-05 07:52 UTC, Amitk-webkul commented
@suraj-webkul 
Please resolve the conflicts.