Drag drop image
bagisto/bagisto pull request #7399
Opened 2023-03-29 07:23 UTC by suraj-webkul

Issue #7157 fixed.

2023-04-03 10:30 UTC, Sanjaybhattwebkul commented
@suraj-webkul 
This is working fine.

2023-04-03 10:31 UTC, Sanjaybhattwebkul submitted a review, later dismissed

2023-04-06 07:55 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/variations.blade.php
> +                    }, 1000);
Improve this.

2023-04-06 08:02 UTC, devansh-webkul commented on packages/Webkul/Attribute/src/Http/Controllers/AttributeController.php
> +        ]);
Improve this.

2023-04-06 08:02 UTC, devansh-webkul requested changes
Changes.

2023-04-06 08:40 UTC, devansh-webkul approved these changes

2023-04-06 10:40 UTC, merged