Added selected count on Mass Action
bagisto/bagisto pull request #7437
Opened 2023-03-31 11:19 UTC by akathuria289

## Issue Reference
#7100

2023-03-31 13:56 UTC, Amitk-webkul commented
@akathuria289 

If there is not any selected row so no need to show the selected title that is already shown. [Here](https://prnt.sc/mxa6ERGOcX7Y)

and No need to show selected tables where the table is not selectable for the data. [Here](https://prnt.sc/oWP_VMRWe4Xr)

2023-04-03 06:34 UTC, akathuria289 commented
@Amitk-webkul Done

2023-04-03 07:11 UTC, Amitk-webkul commented
@akathuria289 
Now It is working fine.

2023-04-04 06:48 UTC, ashishkumar-webkul commented
Checked and Found that this is working fine, I am attaching the video for the reference please check the same.
**Video**


https://user-images.githubusercontent.com/92721837/229710576-a4ed4ef6-258e-49fd-9fca-33a1d8a9dc67.mp4

2023-04-10 08:33 UTC, Sanjaybhattwebkul approved these changes

2023-04-10 09:19 UTC, devansh-webkul requested changes

2023-04-10 09:19 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-filter-tags.vue
> +        "total"
Single qoutes.

2023-04-10 09:19 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/datagrid-plus.vue
> +                        console.log(results);
Remove this.

2023-04-10 09:19 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/datagrid-plus.vue
> +            massActionsToggle:false,
```
massActionsToggle: false,
```

2023-04-10 09:19 UTC, devansh-webkul commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/partials/datagrid-filter-tags.vue
> +        <div class="item-count" v-if="itemCount"> {{ itemCount }} of {{ total }} selected</div>
Translation.

2023-04-11 06:13 UTC, akathuria289 commented on packages/Webkul/Ui/src/Resources/assets/js/components/datagrid/datagrid-plus.vue
> +            massActionsToggle:false,
added

2023-04-11 06:56 UTC, jitendra-webkul approved these changes

2023-04-11 06:57 UTC, merged