#7432 issue_fixed
bagisto/bagisto pull request #7445
Opened 2023-04-03 04:57 UTC by shivamtiwariwebkul

Issue  #7432 fixed 
-> The write-review option should not be visible on product card if Allow Guest Review is disabled
-> this issue has been resolved

2023-04-03 05:23 UTC, Sanjaybhattwebkul approved these changes

2023-04-05 08:29 UTC, devansh-webkul requested changes

2023-04-05 08:29 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/home/new-products.blade.php
>  @endphp
Move all this logic to the controller. This blade file should be clean and should only have the required variables.

2023-04-05 08:29 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/home/new-products.blade.php
> +    :guest-review-status="{{ (Boolean) $guest_review_status ? 'true' : 'false'}}"
Be consistent when type casting if above you using a small case then below should also be small case like bool or boolean.

2023-04-05 08:29 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/home/featured-products.blade.php
>  @endphp
Move all this logic to the controller. This blade file should be clean and should only have the required variables.

2023-04-05 08:29 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/js/UI/components/product-card.vue
> +            <div class="product-rating col-12 no-padding" v-else-if="guestReviewStatus">
All boolean logic should have a `can` or `is` prefix like `canGuestReview`.

Same as `isEnabled`, `isUsed`, `isChecked`, etc.

2023-04-06 08:30 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/views/shop/home/index.blade.php
> +                {!! Blade::render($velocityMetaData->home_page_content, ['guest_review_status' => $config['guestReviewStatus'], 'count' => $config['count'],'direction' => $config['direction']]) !!}
Discussed.

2023-04-06 08:35 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Http/Controllers/HomeController.php
> +        return view($this->_config['view'], compact('sliderData','config'));
Discussed.

2023-04-06 08:36 UTC, devansh-webkul requested changes
Please do the discussed changes.

2023-04-12 09:23 UTC, devansh-webkul commented
I am continuing this.

2023-04-12 09:23 UTC, closed without merging