Issue #7079 fixed
bagisto/bagisto pull request #7447
Opened 2023-04-03 06:19 UTC by rachana-webkul

## Issue Reference
#7079

2023-04-04 08:25 UTC, rachana-webkul commented
it's working from my end,please verify![Screenshot from 2023-04-04 13-45-55](https://user-images.githubusercontent.com/120095673/229732660-12d3707b-e32d-40fe-8e9d-038f6b7ad16c.png)

2023-04-10 08:10 UTC, Sanjaybhattwebkul submitted a review, later dismissed

2023-04-10 09:28 UTC, devansh-webkul requested changes

2023-04-10 09:28 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/catalog/products/accordians/grouped-products.blade.php
> +                    });
Improve this, no need for `$.each` here.

2023-04-14 05:43 UTC, closed without merging