Issue #7419 fixed
bagisto/bagisto pull request #7448
Opened 2023-04-03 06:40 UTC by vijay-webkul

## Issue Reference
#7419

2023-04-03 07:55 UTC, Sanjaybhattwebkul commented
@vijay-webkul 
The **start** and **end** time is **not visible.** please find the screenshot [Here](https://webkul.chatwhizz.com/share/screenshot/642a862e2a666707c408fe0e)

2023-04-04 06:52 UTC, Sanjaybhattwebkul commented
@vijay-webkul 
This is **working fine.**

2023-04-04 06:53 UTC, Sanjaybhattwebkul approved these changes

2023-04-05 09:00 UTC, devansh-webkul requested changes

2023-04-05 09:00 UTC, devansh-webkul commented on packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php
> +        $data['ends_till'] = $data['ends_till'] ? $data['ends_till'] : null;
No need to do these changes.

2023-04-10 07:12 UTC, Sanjaybhattwebkul commented
@vijay-webkul 
Resolved the conflicts.

2023-04-10 11:51 UTC, closed without merging