Filter option mobile view
bagisto/bagisto pull request #7486
Opened 2023-04-06 11:31 UTC by peeyush-webkul

## Issue Reference
#7397

2023-04-10 06:15 UTC, Amitk-webkul commented
@peeyush-webkul 
Now It is working fine. [Here](https://prnt.sc/Eo8bL8qrDHK5)

2023-04-10 06:38 UTC, Sanjaybhattwebkul commented
@peeyush-webkul 
Resolve the **duplicate commits.**

2023-04-10 07:05 UTC, Sanjaybhattwebkul approved these changes

2023-04-10 07:58 UTC, devansh-webkul requested changes

2023-04-10 07:58 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/js/UI/components/header-mobile.vue
> +        }
Improve this.

2023-04-10 07:58 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/js/UI/components/header-mobile.vue
> +    },
Remove all extra lines and aligned them properly.

2023-04-10 07:58 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +
Remove extra line.

2023-04-10 07:58 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +
Same here.

2023-04-10 07:58 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +
Same here.

2023-04-10 07:58 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +
Same here.

2023-04-10 07:58 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +
Same here.

2023-04-10 12:22 UTC, devansh-webkul commented
I am seeing old commits also. Please check.

2023-04-10 14:03 UTC, devansh-webkul commented on packages/Webkul/Velocity/src/Resources/assets/sass/components/media.scss
> +                            }
Add a new line after each closing bracket.

2023-04-14 08:16 UTC, Amitk-webkul commented
@peeyush-webkul 
on the filter page, the page width is not set. [Here](https://prnt.sc/CalcJALkP8QT)

2023-04-17 04:10 UTC, Amitk-webkul commented
@peeyush-webkul 
Not fixed for the sub-category. [Here](https://prnt.sc/_VmTmd9uyoz6)

2023-04-18 05:41 UTC, Amitk-webkul commented
@peeyush-webkul 
It is working fine.[Here](https://prnt.sc/f7mCDT5utu8l)

2023-04-18 05:41 UTC, Amitk-webkul approved these changes

2023-04-19 09:11 UTC, jitendra-webkul approved these changes

2023-04-19 09:11 UTC, merged