Compare page
bagisto/bagisto pull request #7642
Opened 2023-06-09 14:49 UTC by amit-webkul

2023-06-13 08:21 UTC, suraj-webkul requested changes

2023-06-13 08:21 UTC, suraj-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
> +            }
Need imrpovement here.

2023-06-13 08:21 UTC, suraj-webkul commented on packages/Webkul/Customer/src/Models/CompareItem.php
> +     * @return void
Add belongs to return type  here.

2023-06-13 09:49 UTC, suraj-webkul requested changes

2023-06-13 09:49 UTC, suraj-webkul commented on packages/Webkul/Shop/src/Http/Resources/CompareResource.php
> +     * @param  \Illuminate\Http\Request
write @param \Illuminate\Http\Request  $request

2023-06-13 09:49 UTC, suraj-webkul commented on packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
> +                            <p class="text-[16px] font-medium cursor-pointer" v-if="cart.discount_amount == 0">
Break attributes.

2023-06-13 09:49 UTC, suraj-webkul commented on packages/Webkul/Shop/src/Resources/views/checkout/cart/mini-cart.blade.php
> +                            this.cart = response.data.data[0];
check is it works.

2023-06-13 09:49 UTC, suraj-webkul commented on packages/Webkul/Shop/src/Resources/views/compare/index.blade.php
> +                        isCustomer: '{{ auth()->guard('customer')->user() ? "true" : "false" }}' == 'true',
Optimize this one

2023-06-13 09:49 UTC, suraj-webkul commented on packages/Webkul/Shop/src/Resources/views/compare/index.blade.php
> +                                    this.compareItem = response.data.data;
if compareItem contains multiple data then rename it to compareItems

2023-06-13 11:15 UTC, amit-webkul commented on packages/Webkul/Shop/src/Resources/views/compare/index.blade.php
> +                        isCustomer: '{{ auth()->guard('customer')->user() ? "true" : "false" }}' == 'true',
Fixed

2023-06-13 11:15 UTC, amit-webkul commented on packages/Webkul/Shop/src/Resources/views/checkout/cart/index.blade.php
> +                            <p class="text-[16px] font-medium cursor-pointer" v-if="cart.discount_amount == 0">
fixed

2023-06-13 11:15 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Resources/CompareResource.php
> +     * @param  \Illuminate\Http\Request
fixed

2023-06-13 11:15 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/CompareController.php
> +    public function moveCart()
fixed

2023-06-13 11:15 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/CompareController.php
> +    public function moveToWisthlist()
fixed

2023-06-13 11:15 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/CompareController.php
> +            ) {
fixed

2023-06-13 11:15 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/CompareController.php
> +    public function destroy(): JsonResource
fixed

2023-06-13 11:16 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/CompareController.php
> +                foreach ($product_id as $id) {
fixed

2023-06-13 11:16 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/CompareController.php
> +     * @return \Illuminate\View\View
fixed

2023-06-13 11:16 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/CompareController.php
> +     * @param  Webkul\Customer\Repositories\CompareItemRepository  $compareItemsRepository
fixed

2023-06-13 11:16 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
> +                $cart = $cart->where('is_guest', '=', 1)->get();
fixed

2023-06-13 11:16 UTC, amit-webkul commented on packages/Webkul/Customer/src/Models/CompareItem.php
> +     * @return void
fixed

2023-06-13 11:16 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/CartController.php
> +            }
fixed

2023-06-13 14:36 UTC, amit-webkul commented on packages/Webkul/Shop/src/Http/Resources/ProductResource.php
> +            'description' => $this->description,
Fixed

2023-06-14 07:02 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Http/Controllers/API/CompareController.php
> +                }
Do it in a single query.

2023-06-14 10:44 UTC, amit-webkul commented on packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/bottom.blade.php
> +            <a href="{{ route('shop.compare') }}">
Fixed

2023-06-15 06:44 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view.blade.php
> +                                    this.setStorageValue('compared_product', updatedItems);
compare_items

2023-06-15 06:45 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view.blade.php
> +                        return true;
remove the return statement.

2023-06-15 06:51 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view.blade.php
> +                        let updatedItems = [productId];
check this case..

2023-06-15 06:54 UTC, devansh-webkul requested changes
One file change left.

2023-06-15 07:15 UTC, amit-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view.blade.php
> +                        page: 1,
fixed

2023-06-15 07:15 UTC, amit-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view.blade.php
> +                        return true;
fixed

2023-06-15 07:16 UTC, amit-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view.blade.php
> +                                    this.setStorageValue('compared_product', updatedItems);
fixed

2023-06-15 10:23 UTC, devansh-webkul approved these changes

2023-06-15 10:24 UTC, jitendra-webkul approved these changes

2023-06-15 10:24 UTC, merged