Format/refactoring code.
bagisto/bagisto pull request #9242
Opened 2023-12-29 12:20 UTC by suraj-webkul

## Issue Reference

Format/refactoring code.

2023-12-29 13:05 UTC, devansh-webkul commented on packages/Webkul/Admin/tests/Feature/Catalog/ProductTest.php
> +    $procuts = (new ProductFaker())->getSimpleProductFactory()->count(2)->create();
products

2024-01-02 06:57 UTC, devansh-webkul approved these changes

2024-01-02 12:53 UTC, devansh-webkul commented on packages/Webkul/Checkout/src/Database/Factories/CartShippingRateFactory.php
> +            'updated_at'           => $now,
now()

2024-01-02 12:57 UTC, devansh-webkul commented on packages/Webkul/Shop/tests/Feature/Checkout/CheckoutTest.php
> +    session()->put('cart', $cartTemp);
Same here.

2024-01-02 13:09 UTC, devansh-webkul approved these changes

2024-01-02 13:10 UTC, jitendra-webkul approved these changes

2024-01-03 06:02 UTC, devansh-webkul commented on packages/Webkul/Shop/tests/Feature/Checkout/CheckoutTest.php
> +    ]);
Check order_items table also.

2024-01-03 06:04 UTC, devansh-webkul commented on packages/Webkul/Shop/tests/Feature/Checkout/CheckoutTest.php
> +    ]);
Check for order payment and product_ordered_inventory also.

2024-01-03 06:05 UTC, devansh-webkul commented on packages/Webkul/Shop/tests/Feature/Checkout/CheckoutTest.php
> +    ]);
Check cart table for inactive check.

2024-01-03 06:07 UTC, devansh-webkul commented on packages/Webkul/Shop/tests/Feature/Checkout/CheckoutTest.php
> +    ]);
Check addresses table for 'order_billing' and 'order_shipping' type.

2024-01-03 06:08 UTC, devansh-webkul requested changes
- Check 'order_items' table also.

- Check for 'order_payments' and 'product_ordered_inventory' also.

- Check 'cart' table for inactive cart.

- Check 'addresses' table for 'order_billing' and 'order_shipping' type.

2024-01-03 08:32 UTC, devansh-webkul commented on packages/Webkul/Shop/tests/Feature/Checkout/CheckoutTest.php
> +    ]);
Replace this with `product_inventory_indices` and it should be `quantity-1`.

2024-01-03 08:39 UTC, devansh-webkul commented on packages/Webkul/Shop/tests/Feature/Checkout/CheckoutTest.php
> +        'qty_ordered'  => 1,
$cartItem->quantity

2024-01-03 10:07 UTC, devansh-webkul approved these changes

2024-01-03 11:38 UTC, merged