hardcoded status codes replaced with a reference to Order model
bagisto/bagisto pull request #9303
Opened 2024-01-10 23:00 UTC by eness

In my opinion, it is not correct to hard-code values that are used in various parts of the core, such as the Order status codes. In this case, for example, if the key is changed for `STATUS_PENDING` on the Order model, there will be places that don't work. Or in other words, if we statically carry values on the model, why don't we reference them in other code sections?

2024-01-11 05:09 UTC, jitendra-webkul commented
Absolutely, I concur. Instead of utilizing the complete model class, we can import the model at the beginning and utilize only the "Order" model.

Example:

```php
use App\Models\Order;

// ...

$status = Order::STATUS_COMPLETED;
```

2024-01-11 14:07 UTC, eness commented
Actually imho, these statuses should be directly managable from database (e.g in a order_stasuses table).

On the other hand, in my commits above there is another issue that might appear. I offered to reference Model instances directly but since the core gives developer ability to bind their own customized model over Contracts, using namespace of the official Order model might not be ideal. For example if I implement my own model such as MyOrder and define my statuses as constants into it, the bagisto core would not be aware of these statuses as it does reference its own Order model.

Thus, it's better to manage them inside db and generate helpers to use them in the codebase.

2024-01-11 14:28 UTC, devansh-webkul commented
This is in our road map to provide the custom status, currently we have to go with this.

2024-01-15 14:19 UTC, devansh-webkul requested changes
Please import the namespace wherever its possible.

2024-01-15 14:19 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Config/system.php
> +                        'value' => \Webkul\Sales\Models\Order::STATUS_PENDING,
Please import the namespace.

2024-01-15 14:19 UTC, devansh-webkul commented on packages/Webkul/Admin/src/DataGrids/Customers/CustomerDataGrid.php
> +                    return $q->whereNotIn('status', [\Webkul\Sales\Models\Order::STATUS_CANCELED, \Webkul\Sales\Models\Order::STATUS_CLOSED])
Same here.

2024-01-15 14:19 UTC, devansh-webkul commented on packages/Webkul/Admin/src/DataGrids/Sales/OrderDataGrid.php
> +                \Webkul\Sales\Models\Order::STATUS_PROCESSING      => trans('admin::app.sales.orders.index.datagrid.processing'),
Same here.

2024-01-15 14:19 UTC, devansh-webkul commented on packages/Webkul/Admin/src/DataGrids/Sales/OrderDataGrid.php
> +                    case \Webkul\Sales\Models\Order::STATUS_PROCESSING:
Same here.

2024-01-15 14:19 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Http/Controllers/Sales/TransactionController.php
> +                $this->orderRepository->updateOrderStatus($order, \Webkul\Sales\Models\Order::STATUS_COMPLETED);
Same here.

2024-01-21 20:59 UTC, eness commented
> Please import the namespace wherever its possible.

seems to be these changes have already been made.

2024-01-23 10:06 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Config/system.php
> +                        'value' => \Webkul\Sales\Models\Order::STATUS_PENDING,
We mean to say like this,

~~~php
use Webkul\Sales\Models\Order;
...
'value' => Order::STATUS_PENDING
~~~

2024-01-23 10:06 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Config/system.php
> +                        'value' => \Webkul\Sales\Models\Order::STATUS_PENDING_PAYMENT,
~~~php
use Webkul\Sales\Models\Order;
...
'value' => Order::STATUS_PENDING_PAYMENT
~~~

2024-01-25 00:07 UTC, eness commented on packages/Webkul/Admin/src/Config/system.php
> +                        'value' => \Webkul\Sales\Models\Order::STATUS_PENDING_PAYMENT,
done.

2024-01-25 07:27 UTC, devansh-webkul approved these changes

2024-01-25 08:51 UTC, merged