Fixed issue #9335
bagisto/bagisto pull request #9348
Opened 2024-01-18 14:20 UTC by shivendra-webkul

## Issue Reference
Fixed issue #9335

2024-01-18 14:47 UTC, suraj-webkul commented on packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php
> +        $data['ends_till'] = ! empty($data['ends_till']) ? $data['ends_till'] : null;
You can use below syntax for achieve same.
```php
$data['starts_from'] ??= null;

2024-01-18 14:47 UTC, suraj-webkul commented on packages/Webkul/CartRule/src/Repositories/CartRuleRepository.php
> +            'ends_till'   => ! empty($data['ends_till']) ? $data['ends_till'] : null,
Read above comment

2024-01-18 14:48 UTC, suraj-webkul requested changes
You can use below syntax for achieve same.

```php
$data['starts_from'] ??= null;

2024-01-19 06:04 UTC, devansh-webkul approved these changes

2024-01-19 07:31 UTC, jitendra-webkul approved these changes

2024-01-19 07:31 UTC, merged