extra period fixed
bagisto/bagisto pull request #9351
Opened 2024-01-20 21:28 UTC by eness

extra period used by mistake, fixed.

2024-01-22 05:29 UTC, ashishkumar-webkul requested changes
@shivendra-webkul 
Please check this again.

2024-01-22 05:31 UTC, shivendra-webkul approved these changes

2024-01-22 05:53 UTC, ashishkumar-webkul approved these changes

2024-01-22 12:38 UTC, ashishkumar-webkul commented
@eness and @shivendra-webkul 

As I have checked and extra dot has been removed, please check the screenshot after merging the code.

**Screenshot**

![Uploading Screenshot from 2024-01-22 18-07-31.png…]()

2024-01-23 10:01 UTC, devansh-webkul approved these changes

2024-01-23 10:01 UTC, merged