Minor issues
bagisto/bagisto pull request #9519
Opened 2024-02-23 12:31 UTC by shivendra-webkul

## Issue Reference
Add confirm modal on mini cart item delete.
Remove top header when currency and locale count is less then 1.

2024-02-27 09:48 UTC, ashishkumar-webkul commented
@shivendra-webkul 
Checked and Found that some issues are fixed and 1 issue is still remaing. 

Issues which are fixed.

1. Cart warning message

![Warning](https://github.com/bagisto/bagisto/assets/92721837/7275b463-a67f-4614-a405-0e2e3bf65796)

2. Additional Information Hidden.

![Additional Feature](https://github.com/bagisto/bagisto/assets/92721837/6d6120f3-fdce-471f-9079-3acea8c963eb)

3. Header Removed when single locale or currency is presenr for shop.

![Header](https://github.com/bagisto/bagisto/assets/92721837/646f5183-aee4-461a-b6c6-68d5dad1b423)


Attribute issue is still appearing.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/bbaf99aa-de9b-4a00-89a2-97a22c72e5ec

2024-02-27 10:04 UTC, shivendra-webkul commented
@ashishkumar-webkul Attribute issue is not appearing. It is working fine please check again.
Reference:- https://webkul.chatwhizz.com/share/view-recording/65ddb0b9095e200579478d8a

2024-02-27 10:20 UTC, ashishkumar-webkul commented
@shivendra-webkul 

Checked the same concern with a fresh setup and then found that the issue has been fixed and working fine. Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/ca704620-6852-4672-89fc-1b2c548217d3

2024-02-28 07:32 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Http/Controllers/Sales/TransactionController.php
> +        $transaction = $this->orderTransactionRepository->findOrFail($id)->toArray();
Remove toArray

2024-02-28 07:33 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Http/Controllers/Sales/TransactionController.php
>          return new JsonResponse([
Use Transaction Resource.

2024-02-28 07:34 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view.blade.php
> +    });
~~~php
collect($customAttributeValues)->filter(fn ($item) => ! empty($item['value']));
~~~

2024-02-28 07:35 UTC, devansh-webkul requested changes
Check the above changes.

2024-02-28 07:58 UTC, ashishkumar-webkul commented
@shivendra-webkul 

Please fix all the changes and again assign back for testing.

2024-02-28 12:57 UTC, shivendra-webkul commented on packages/Webkul/Admin/src/Http/Controllers/Sales/TransactionController.php
>          return new JsonResponse([
Done

2024-02-28 12:57 UTC, shivendra-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view.blade.php
> +    });
Done

2024-02-29 07:03 UTC, ashishkumar-webkul commented
@shivendra-webkul 

Please check there are some test's which are failed in thr PR, please verify the issues in test case fails.

2024-02-29 11:36 UTC, suraj-webkul approved these changes

2024-02-29 11:36 UTC, suraj-webkul commented on packages/Webkul/Admin/src/Http/Resources/TransactionResource.php
> +    public function toArray($request)
You can use strictly return type of this method and use params like
```php
public function toArray(Request $request): array
{
// ......
}
```

2024-02-29 11:41 UTC, suraj-webkul commented
@shivendra-webkul 

Your test case failing due to routes renaming....

2024-03-01 05:20 UTC, devansh-webkul approved these changes

2024-03-01 05:21 UTC, merged