theme: filterable dynamic options.
bagisto/bagisto pull request #9570
Opened 2024-03-05 11:52 UTC by suraj-webkul

2024-03-26 07:02 UTC, ashishkumar-webkul commented
@suraj-webkul 

There are some conflicts in this PR. Please fix the PR conflicts.

2024-04-02 12:19 UTC, suraj-webkul commented
Resolved conflicts.

2024-04-03 11:06 UTC, devansh-webkul requested changes

2024-04-04 12:37 UTC, suraj-webkul commented on packages/Webkul/Admin/src/Resources/views/settings/themes/edit/product-carousel.blade.php
> +
done

2024-05-06 12:31 UTC, devansh-webkul submitted a review, later dismissed

2024-05-07 08:07 UTC, ashishkumar-webkul commented
Checked and Found that the filters are working fine, please check the video for reference. 

**Video**

https://github.com/bagisto/bagisto/assets/92721837/60378deb-6d28-4b6f-a9a5-1bc4e9268ac2

2024-05-07 12:50 UTC, ashishkumar-webkul commented
Need to fix the issue of static content view, page is not appearing properly. Please fix the issue.

**Video**

2024-05-14 06:34 UTC, devansh-webkul commented
Conflicts.

2024-05-14 10:57 UTC, ashishkumar-webkul commented
Checked and found that the issue related to the static content pages in theme section and also the product crousal concern are added with filters, hence the issue has been fixed and working fine. Please check the video for reference.

**Video**


https://github.com/bagisto/bagisto/assets/92721837/ce1b4530-e07a-4726-9177-ed4163f4a089

2024-05-14 10:58 UTC, ashishkumar-webkul submitted a review, later dismissed
checked and found that he static content issue fixed and also product crousal is added with the attribute options.

2024-05-14 10:59 UTC, devansh-webkul approved these changes

2024-05-27 10:35 UTC, devansh-webkul approved these changes

2024-05-30 12:27 UTC, merged