Prevent guests to add a downloadable product
bagisto/bagisto pull request #9605
Opened 2024-03-27 15:27 UTC by AmooAti

## Issue Reference
#9542 

## Description
Hi, I've implemented the requested enhancement and removed some tests regarding testing downloadable products when the customer is not logged in.
But maybe having a `redirect_url` in the session to redirect customers back to the product page has a better UX.

## How To Test This?
Follow the mentioned issue description.

2024-04-02 09:54 UTC, devansh-webkul commented on packages/Webkul/Shop/tests/Feature/Checkout/CartTest.php
> +    $this->loginAsCustomer();
This is part of act not arrange. This line shoule be after act and assert comment.

2024-04-02 09:56 UTC, devansh-webkul requested changes
Hello @AmooAti,

Thank you for the contribution, please look at the minor changes.

2024-04-02 09:56 UTC, devansh-webkul commented on packages/Webkul/Shop/tests/Feature/Product/Prices/DownloadableTest.php
> +    $this->loginAsCustomer();
Same here.

2024-04-02 09:56 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view.blade.php
> +                                    if(response.data.data.redirect) {
Add space after if.

2024-04-02 17:13 UTC, AmooAti commented
Hello @devansh-webkul 
Thank you for your review. It was an excellent point, and I appreciate it.
I've just made changes.

2024-04-03 04:09 UTC, devansh-webkul commented
Hi @AmooAti,

I just discussed this feature, but as per ou flow we dont need this PR because we are having different flow here. Guest user can add to cart at the time of checkout we use login feature there.

Sorry for this, but this pull request as of now cant be merged.

2024-04-03 10:48 UTC, closed without merging