Fixed minor issues
bagisto/bagisto pull request #9619
Opened 2024-04-03 07:20 UTC by shivendra-webkul

## Issue Reference
Fixed minor issues

2024-04-05 13:04 UTC, suraj-webkul submitted a review, later dismissed

2024-04-12 08:19 UTC, amit-webkul submitted a review, later dismissed

2024-04-12 08:43 UTC, ashishkumar-webkul commented
@shivendra-webkul 

Checked and found that the issues has been fixed and working fine.
1. In Channel -> now it will show default -> https://prnt.sc/xtUaG5oxGrvq
2. In CMS Page -> Channel Checkbox centre allignment done -> https://prnt.sc/jLw70glrUgX0

2024-04-15 05:05 UTC, devansh-webkul requested changes

2024-04-15 05:05 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Resources/views/settings/channels/create.blade.php
> +                            :value="old('theme', array_key_first(config('themes.shop')))"
This is getting the first one, not the default one.

2024-04-16 12:41 UTC, ashishkumar-webkul commented
@shivendra-webkul

Checked and found that the issues has been fixed and working fine.

1. In Channel -> now it will show default -> https://scrsht.com/11c5d2a0
2. In CMS Page -> Channel Checkbox centre allignment done -> https://scrsht.com/3aa90f5c

2024-04-17 10:15 UTC, jitendra-webkul approved these changes

2024-04-17 10:16 UTC, merged