Refactor customers-account address translation
bagisto/bagisto pull request #9631
Opened 2024-04-08 11:11 UTC by shivendra-webkul

## Issue Reference
Refactor customers-account address translation

2024-04-24 10:21 UTC, amit-webkul requested changes

2024-04-24 10:21 UTC, amit-webkul commented on packages/Webkul/Shop/src/Resources/views/components/layouts/header/desktop/top.blade.php
> +                @lang('shop::app.components.layouts.header.desktop.top.offer') <a href="{{ route('shop.home.index') }}" class="underline"> @lang('shop::app.components.layouts.header.desktop.top.shop-
We can break this up into multiple lines.

2024-04-24 10:21 UTC, amit-webkul commented on packages/Webkul/Shop/src/Resources/lang/en/app.php
> +                    'add-address'    => 'Add Address',
I think this add-address key is useless. Please check and remove this one.

2024-05-02 13:21 UTC, devansh-webkul submitted a review, later dismissed

2024-05-03 07:14 UTC, merged