Added review-image zoomer component
bagisto/bagisto pull request #9754
Opened 2024-05-03 11:43 UTC by shivendra-webkul

## Issue Reference
Added review-image zoomer component

2024-05-06 12:34 UTC, devansh-webkul requested changes

2024-05-06 12:34 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
> +                        @click="isImageZooming =! isImageZooming"
Fix this.

2024-05-06 13:08 UTC, shivendra-webkul commented on packages/Webkul/Shop/src/Resources/views/products/view/gallery.blade.php
> +                        @click="isImageZooming =! isImageZooming"
Done

2024-05-06 13:16 UTC, devansh-webkul approved these changes

2024-05-07 11:55 UTC, devansh-webkul submitted a review, later dismissed

2024-05-08 05:59 UTC, ashishkumar-webkul commented
Checked and Found that Images or videos in vertical size are not appearing properly, which need to be managed.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/4a8feded-09ef-4057-b1d6-c3e92e71b5b0

2024-05-08 07:00 UTC, ashishkumar-webkul commented
Checked and Found that  the images and banner both are appearing clear in the review zoomer. Please check  the video for the reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/67a09895-ca0e-426c-9417-f51e363a8381

2024-05-09 12:16 UTC, jitendra-webkul approved these changes

2024-05-09 12:16 UTC, merged