Fix Social Share For mobile view.
bagisto/bagisto pull request #9773
Opened 2024-05-09 05:18 UTC by amit-webkul

## Issue Reference
#9772

2024-05-13 06:10 UTC, ashishkumar-webkul commented
Checked and Found that warning pop-up is appearing when I am checking the PR, It is not compatible with browser. Please check the video for reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/4c7e9aec-3aff-47b0-a497-cb4eff484f7c

2024-05-14 05:33 UTC, amit-webkul commented
@ashishkumar-webkul ｓiｒ

I have checked in mobile phone the social share is working fine please find the below attachment. 

https://github.com/bagisto/bagisto/assets/121479029/498e8e19-dcd6-4706-bd1c-8b7eaf81e09c

2024-05-14 05:37 UTC, devansh-webkul requested changes

2024-05-14 05:37 UTC, devansh-webkul commented on packages/Webkul/SocialShare/src/Resources/views/share.blade.php
> +                var productUrl = "{{ route('shop.product_or_category.index', [$product->url_key]) }}";
Use let.

2024-05-14 05:37 UTC, devansh-webkul commented on packages/Webkul/SocialShare/src/Resources/views/share.blade.php
> +            <a href="#" onclick="shareProduct()">
javascript:void(0);

2024-05-14 05:46 UTC, amit-webkul commented on packages/Webkul/SocialShare/src/Resources/views/share.blade.php
> +                var productUrl = "{{ route('shop.product_or_category.index', [$product->url_key]) }}";
Done sir

2024-05-14 05:46 UTC, amit-webkul commented on packages/Webkul/SocialShare/src/Resources/views/share.blade.php
> +            <a href="#" onclick="shareProduct()">
Done sir

2024-05-14 05:52 UTC, ashishkumar-webkul commented
Checked and found that the social share is working, please check the video for reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/5bada79a-07dc-4cf2-a6e3-9e1a124356b1

2024-05-14 06:25 UTC, devansh-webkul approved these changes

2024-05-14 06:25 UTC, jitendra-webkul approved these changes

2024-05-14 06:26 UTC, merged