Fixed issue #9852
bagisto/bagisto pull request #9874
Opened 2024-06-05 11:27 UTC by shivendra-webkul

## Issue Reference
Fixed issue #9852

2024-06-06 07:46 UTC, ashishkumar-webkul commented
@shivendra-webkul 
I have checked the PR with almost all locale and now it is working fine. As now no validation is appearing and it is accepting the desired locale translation which is required.

Please check the video for the reference.

**Video**

https://github.com/bagisto/bagisto/assets/92721837/d76587ff-6254-44a7-ad91-aa06dfd2ed4c

2024-06-07 06:30 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Http/Requests/AddressRequest.php
> +namespace Webkul\admin\Http\Requests;
Check namespace.

2024-06-07 06:31 UTC, devansh-webkul requested changes

2024-06-07 06:31 UTC, devansh-webkul commented on packages/Webkul/Admin/src/Http/Requests/CartAddressRequest.php
>              "{$addressType}.phone"      => ['required', new PhoneNumber],
Remove string.

2024-06-07 06:31 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Http/Requests/CartAddressRequest.php
> +            "{$addressType}.postcode"   => core()->isPostCodeRequired() ? ['required', 'numeric'] : ['numeric'],
Remove string.

2024-06-07 06:31 UTC, devansh-webkul commented on packages/Webkul/Shop/src/Http/Requests/Customer/AddressRequest.php
>              'postcode'     => core()->isPostCodeRequired() ? ['required', 'numeric'] : ['numeric'],
Remove string.

2024-06-07 07:18 UTC, shivendra-webkul commented on packages/Webkul/Shop/src/Http/Requests/Customer/AddressRequest.php
>              'postcode'     => core()->isPostCodeRequired() ? ['required', 'numeric'] : ['numeric'],
Done

2024-06-07 07:18 UTC, shivendra-webkul commented on packages/Webkul/Shop/src/Http/Requests/CartAddressRequest.php
> +            "{$addressType}.postcode"   => core()->isPostCodeRequired() ? ['required', 'numeric'] : ['numeric'],
Done

2024-06-07 07:19 UTC, shivendra-webkul commented on packages/Webkul/Admin/src/Http/Requests/CartAddressRequest.php
>              "{$addressType}.phone"      => ['required', new PhoneNumber],
Done

2024-06-07 07:19 UTC, shivendra-webkul commented on packages/Webkul/Admin/src/Http/Requests/AddressRequest.php
> +namespace Webkul\admin\Http\Requests;
Done

2024-06-10 10:45 UTC, jitendra-webkul approved these changes

2024-06-10 10:45 UTC, merged